keras-team/keras-io

- templates/api/optimizers/index.md
Signed-off-by: Siu Ching Pong -Asuka Kenji- <asukakenji@users.noreply.github.com>
> Fixed Issue #23

- examples/vision/grad_cam.py
- The image_size of 299x299 is passed in this example instead of 224x224
> fix wrong image size in comments for grad_cam example

- examples/vision/grad_cam.py
- examples/vision/ipynb/grad_cam.ipynb
- examples/vision/md/grad_cam.md
- This is an update to the previous PR: https://github.com/keras-team/keras-io/pull/33 as previous PR was not updated in [Keras docs](https://keras.io/examples/vision/grad_cam/)
> fix wrong img_size in comments for Vision:GradCAM

- examples/nlp/text_classification_from_scratch.py
https://github.com/keras-team/keras-io/issues/41
> Add info on validation dataset to code example (re: #41)

- guides/customizing_what_happens_in_fit.py
Updates the guide with required TF version info.
Fixes https://github.com/tensorflow/tensorflow/issues/40041
> update customizing_what_happens_in_fit guide with TF version

- examples/vision/metric_learning.py
A minimal example of metric learning using cosine similarity as logits for a softmax. Unsure the level of description expected on keras.io regarding the approach of using sims as logits, have included what is the minimal info.
> metric learning eg

- templates/about.md
/guides/model_subclassing/ --> /guides/making_new_layers_and_models_via_subclassing/
Thanks. :)
> Correct model subclassing link.

- tf/_keras_guide_toc.yaml
Can add all the other files to the TOC in a later PR. Or you can rearrange them as you see fit :)
> Add keras TOC file

- examples/structured_data/collaborative_filtering_movielens.py
- examples/structured_data/ipynb/collaborative_filtering_movielens.ipynb
- examples/structured_data/md/collaborative_filtering_movielens.md
Creating new PR as advised by @fchollet to incorporate a small big in the collab filtering code when checking movies to recommend to user. 
Signed-off-by: Siddhartha Banerjee <sidd2006@gmail.com>
> add variable changes

- examples/nlp/ipynb/text_extraction_with_bert.ipynb
- examples/nlp/md/text_extraction_with_bert.md
- examples/nlp/text_extraction_with_bert.py
> text_extraction_with_bert fix typo

- call_for_contributions.md
@Korusuke and I would like to work on the StyleGAN implementation as noted in #144
> Claiming StyleGAN Implementation Issue

- templates/getting_started/ecosystem.md
'embdeded' --> 'embedded'
Thanks
> Fix a type in ecosystem.md

- guides/writing_a_training_loop_from_scratch.py
> Update writing_a_training_loop_from_scratch.py small typo fixing

- scripts/autogen.py
- scripts/tutobooks.py
Removing hardcoded filename separator to allow cross platform compatibility
> Cross platform compatibility

- guides/functional_api.py
- tf/functional.ipynb
This PR fixes functional API page grammatical errors.
> Fix functional API page grammatical errors

- examples/nlp/bidirectional_lstm_imdb.py
- Explain what sequence.pad_sequences is used for in the example
- add arguments(optimizer, loss)
> Update lstm NLP example

- guides/training_with_built_in_methods.py
- tf/train_and_evaluate.ipynb
This PR fixes train-and-evaluate page grammatical errors.
> Fix train-and-evaluate page grammatical errors

- guides/distributed_training.py
This PR fixes distributed training page grammatical errors.
> Fix distributed training page grammatical errors

- guides/md/serialization_and_saving.md
Continuation of  [#191 PR ](https://github.com/keras-team/keras-io/pull/191)
> fix wrong output files of my_model directory

- guides/customizing_what_happens_in_fit.py
This PR fixes customizing doc grammatical errors.
> Fix customizing doc grammatical errors

- guides/functional_api.py
- guides/intro_to_keras_for_engineers.py
This PR fixes functional API doc grammatical errors.
> Fix functional api doc grammatical errors

- guides/distributed_training.py
This PR fixes distributed training doc grammatical errors.
> Fix distributed training doc grammatical errors

- guides/intro_to_keras_for_researchers.py
- guides/making_new_layers_and_models_via_subclassing.py
This PR fixes intro doc grammatical errors.
> Fix intro doc grammatical errors

- guides/writing_a_training_loop_from_scratch.py
This PR fixes writing a training loop doc grammatical errors.
> Fix writing a training loop doc grammatical errors

- guides/working_with_rnns.py
This PR fixes working with mns doc grammatical errors.
> Fix working with mns doc grammatical errors

- guides/transfer_learning.py
- guides/understanding_masking_and_padding.py
This PR fixes transfer learning doc grammatical errors.
> Fix transfer learning doc grammatical errors

- guides/md/transfer_learning.md
- guides/md/understanding_masking_and_padding.md
This PR fixes grammatical errors in generated .md files.
> Fix grammatical errors in generated .md files

- guides/intro_to_keras_for_engineers.py
This PR fixes intro to Keras for engineers doc grammatical errors.
> Fix intro to keras for engineers doc grammatical errors

- examples/nlp/pretrained_word_embeddings.py
The statement had no effect in the code.
> Removed an unused statement

- guides/transfer_learning.py
The link to "Making new Layers & Models via subclassing" is broken
> Updating broken link

- examples/timeseries/timeseries_anomaly_detection.py
I really enjoyed studying this new sample. This PR does not change any of the Keras functionality of the sample.
In the data pipeline I simplified the code by using pandas time series and charting features. Hopefully this makes the code easier to understand and follow.
Please let me know if the changes are good, and I will add the generated files.
Signed-off-by: Robert Altena <Rob@Ra-ai.com>
> timeseries_anomaly_detection : "a little less python looping, a little more pandas action."

- scripts/models_master.py
> Add save_weights() method in models_master.py

- templates/getting_started/faq.md
This PR fixes broken link for question section "What do "sample", "batch", and "epoch" mean?"
> Fix link to question

- theme/landing.html
Changed 'tighly-connected' to 'tightly-connected' on Keras landing page
> Fixed typo on landing page

- guides/ipynb/sequential_model.ipynb
- guides/ipynb/serialization_and_saving.ipynb
- guides/md/sequential_model.md
- guides/md/serialization_and_saving.md
- guides/sequential_model.py
- guides/serialization_and_saving.py
Easy navigation and easy reading for others
> Fix broken url in docs

- examples/generative/ipynb/pixelcnn.ipynb
- examples/generative/md/pixelcnn.md
- examples/generative/pixelcnn.py
A few minor small things including spelling.
The pixel intensity changes from 0 to 255, though the images (not pixels) are black and white, so I propose the following:
```diff
- ...pixels values are either black or white
+ ...pixel values range from white (0) to black (255).
```
Thank you `keras-team` and @fchollet
> Lint Keras - PixelCNN example

- examples/generative/ipynb/text_generation_with_miniature_gpt.ipynb
- examples/generative/md/text_generation_with_miniature_gpt.md
- examples/generative/text_generation_with_miniature_gpt.py
Really enjoyed this small GPT example and noticed a few things. This PR implements a few small changes including spelling fixes, using the sentence-case rule for the title, and adding definite/indefinite articles. Also, "Transformer" is apparently referred to with a capital "T". Any suggestions/feedback welcome. Thanks `keras-team` and @fchollet 👍
> Lint Keras - Text generation with a miniature GPT example

- examples/generative/ipynb/wgan_gp.ipynb
- examples/generative/md/wgan_gp.md
- examples/generative/wgan_gp.py
Spotted a few tiny things. Thanks `keras-team` and @fchollet
> Lint the Keras - Wasserstein GAN (WGAN) with Gradient Penalty (GP) example

- guides/ipynb/making_new_layers_and_models_via_subclassing.ipynb
- guides/making_new_layers_and_models_via_subclassing.py
- guides/md/making_new_layers_and_models_via_subclassing.md
> Correct spelling mistake

- guides/ipynb/preprocessing_layers.ipynb
- guides/md/preprocessing_layers.md
- guides/preprocessing_layers.py
Fixes typo (s/if/of/) in the preprocessing layers documentation.
> Fixes typo (s/if/of/) in the preprocessing layers documentation.

- examples/structured_data/ipynb/movielens_recommendations_transformers.ipynb
I couldn't open this notebook due to extra comma
> Fix not valid Json

- templates/guides/index.md
> Fixing typos in the Doc

- guides/training_with_built_in_methods.py
A few minor suggestions for _Training & evaluation with the built-in methods_ after a quick glance. Note the method name formatting, such as `fit()` and `Model.fit()` (in line with the Google/TensorFlow style guides), as well as args like `history` and `epochs`). Let me know what you think @fchollet . An thanks for writing Deep Learning with Python v1, it's a great book 👍
> Lint Keras.io Training & evaluation with the built-in methods

- examples/vision/ipynb/mixup.ipynb
- examples/vision/md/mixup.md
- examples/vision/mixup.py
> Fix hardcoding of alpha variable in mix_up function in mixup.md and mixup.ipynb

- examples/timeseries/ipynb/timeseries_anomaly_detection.ipynb
- examples/timeseries/md/timeseries_anomaly_detection.md
- examples/timeseries/timeseries_anomaly_detection.py
I remove unnecessary method in timeseries_anomaly_detection.py.
> remove unnecessary method

- examples/timeseries/ipynb/timeseries_weather_forecasting.ipynb
- examples/timeseries/md/timeseries_weather_forecasting.md
- examples/timeseries/timeseries_weather_forecasting.py
PR to fix a typo in a formula.
> Fix typo in formula.

- examples/nlp/ipynb/ner_transformers.ipynb
- examples/nlp/md/ner_transformers.md
- examples/nlp/ner_transformers.py
This PR creates a new example for a simple transformers based named entity recognition model. @fchollet I have closed my earlier [PR](https://github.com/keras-team/keras-io/pull/508) and decided to create a simple example of NER rather than the earlier joint NER and sentence classification example since you mentioned Keras doesn't have any NER example currently. I can make another example of a simple transformer based joint NER and sentence classification if you think that will be helpful too.
Also like I had earlier mentioned, I am using HuggingFace's datasets library only for the data.
> Added an example of a simple transformers based NER

- examples/rl/deep_q_network_breakout.py
Added necessary prerequisite to instruction
Response to #511 (comment)
> Updated add dependencies

- examples/timeseries/ipynb/timeseries_transformer_classification.ipynb
- examples/timeseries/md/timeseries_transformer_classification.md
- examples/timeseries/timeseries_transformer_classification.py
I originally implemented this on [colab](https://colab.research.google.com/drive/1sdXiBKNHGA91vTtgLpfbks3TBpJURfEW?usp=sharing) and my tiny gtx 1060 6gb crashes out of memory when producing the .ipynbs locally, not sure on how to proceed with the `.ipynb` generation.
> Add time series transformer classification example

- examples/timeseries/md/timeseries_classification_transformer.md
Fix broken links to Colab notebook and Python source in timeseries_classification_transformer.md
> Fix broken links in timeseries_classification_transformer.md

- Dockerfile
Docker build command does not work, see #412
> Set TF_VERSION=2.5.0

- templates/getting_started/faq.md
> Update Keras FAQ page

- templates/getting_started/faq.md
Update the answer to the question: What if I need to customize what `fit()` does?
> Update FAQ page

- guides/keras_tuner/getting_started.py
resolves https://github.com/keras-team/keras-tuner/issues/263
> Add tutorial for custom objective to KerasTuner

- guides/making_new_layers_and_models_via_subclassing.py
...according to fchollet. This complements the docstring change in base_layer.py.
> Doc update: Keras layer state can be created as late as first call()

- examples/graph/gnn_citations.py
- examples/graph/ipynb/gnn_citations.ipynb
- examples/graph/md/gnn_citations.md
Fixing bug in Issue #714 by changing single line in call() function of the GNNNodeClassifier() class.
> Fixing issue #714 by changing call() of class GNNNodeClassifier()

- call_for_contributions.md
@ksalama what are your thoughts on adding an example on the call added in this PR?
> Update call_for_contributions.md to include MoE

- templates/api/applications/index.md
> Minor correction in api.applications.index.md

- examples/vision/ipynb/nerf.ipynb
- examples/vision/md/nerf.md
- examples/vision/nerf.py
We have covered an in-depth implementation of NeRF in PyImageSearch. We wanted to link them here for anyone interested.
> Adding PyImageSearch BlogPost links

- examples/graph/mpnn-molecular-graphs.py
Main/notable updates:
1. `unsorted_segment_sum` now used instead of `segment_sum` to deal with edge cases (where the last node has no edges). So the implementation is now more robust.
2. Trainable variables are given names to allow saving the model (an issue brought up before)
3. Functional model simplified by putting partition+padding and average pooling inside the transformer encoder (now named `TransformerEncoderReadout`).
4. Text/math notation explaining the 'message passing' somewhat simplified for easier reading.
5. Abbreviation ("MPNN") added to title.
6. URL had changed for MoleculeNet website (referenced in the tutorial). Now updated accordingly.
7. "`atom_partition_indices`" changed to "`molecule_indicator`" (makes more sense).
8. Conclusions slightly modified.
> update mpnn tutorial

- guides/ipynb/understanding_masking_and_padding.ipynb
- guides/md/understanding_masking_and_padding.md
- guides/understanding_masking_and_padding.py
"Note that you could" -> "Note that you could use"
> Grammar nit in comment

- examples/nlp/ipynb/question_answering.ipynb
- examples/nlp/md/question_answering.md
- examples/nlp/question-answering.py
- examples/nlp/question_answering.py
Hello 👋 
I wanted to add an example script on Question Answering using 🤗 Transformers but I ran across an issue with autogeneration of notebooks from script. (I formatted the script and there's nothing wrong with the style, style tests pass)
See [this issue I opened](https://github.com/keras-team/keras-io/issues/774) about it. Maybe I am mistaken in a step. Opening this as a draft PR since I couldn't autogenerate the notebook.
cc'ing here: @fchollet (because I don't know anyone else I can ask from 😔)
> Question answering with Transformers example added

- scripts/master.py
- templates/api/applications/index.md
I updated the documentation for EfficientNetV2 models, which were added in [this PR](https://github.com/keras-team/keras/pull/14935).
> Added EfficientNetV2 docs.

- guides/ipynb/keras_tuner/custom_tuner.ipynb
- guides/ipynb/keras_tuner/distributed_tuning.ipynb
- guides/ipynb/keras_tuner/getting_started.ipynb
- guides/ipynb/keras_tuner/tailor_the_search_space.ipynb
- guides/keras_tuner/custom_tuner.py
- guides/keras_tuner/distributed_tuning.py
- guides/keras_tuner/getting_started.py
- guides/keras_tuner/tailor_the_search_space.py
- guides/md/keras_tuner/custom_tuner.md
- guides/md/keras_tuner/distributed_tuning.md
- guides/md/keras_tuner/getting_started.md
- guides/md/keras_tuner/tailor_the_search_space.md
The `pip install` block of the KerasTuner guides were incorrect.
This PR fixes them.
> fix kt pip install block

- call_for_contributions.md
@fchollet 
Also, I wanted to ask if it's possible to revisit this call on "Keras reproducibility recipes"?
> Add a call for contribution for a guide on reporting model efficiency

- examples/vision/deit.py
- examples/vision/ipynb/deit.ipynb
- examples/vision/md/deit.md
Main repository: https://github.com/sayakpaul/deit-tf/.
> Add an example on distilling ViTs through attention

- templates/about.md
Made this change according to the TF requirements.
https://www.tensorflow.org/install/pip
> Update the required Python version

- guides/preprocessing_layers.py
> Remove the CPU scope for tf-idf adapt

- examples/vision/captcha_ocr.py
- examples/vision/handwriting_recognition.py
- examples/vision/ipynb/captcha_ocr.ipynb
- examples/vision/ipynb/handwriting_recognition.ipynb
- examples/vision/md/captcha_ocr.md
- examples/vision/md/handwriting_recognition.md
The PR will fix the problem explained in [this](https://stackoverflow.com/questions/68153448/how-to-correctly-save-and-load-a-model-with-custom-ctc-layer-keras-example/70731125#70731125) StackOverflow question.
> Fix characters set inconsistency

- examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb
- examples/nlp/neural_machine_translation_with_transformer.py
model.save doesn't work without these changes
```
NotImplementedError: 
Layer PositionalEmbedding has arguments ['self', 'sequence_length', 'vocab_size', 'embed_dim']
in `__init__` and therefore must override `get_config()`.
Example:
class CustomLayer(keras.layers.Layer):
def __init__(self, arg1, arg2):
super().__init__()
self.arg1 = arg1
self.arg2 = arg2
def get_config(self):
config = super().get_config()
config.update({
"arg1": self.arg1,
"arg2": self.arg2,
})
return config
```
> added getconfig in neural machine translation

- guides/ipynb/serialization_and_saving.ipynb
- guides/md/serialization_and_saving.md
- guides/serialization_and_saving.py
Fixed spelling mistakes at lines 227 and 230
> Fixed spelling mistakes

- examples/generative/ddim.py
Added a detailed example on denoising diffusion generative models, using the Oxford Flowers dataset.
Results gif [here](https://i.imgur.com/gyc8eZX.gif)
> Code Example: Denoising diffusion implicit models

- examples/generative/ipynb/molecule_generation.ipynb
- examples/generative/md/molecule_generation.md
- examples/generative/molecule_generation.py
As a part of hugs keras sprint, this example was updated with model hub and space demo
Generative
- molecule_generation
> add space and model hub for molecule generation with VAE example

- examples/nlp/ipynb/nl_image_search.ipynb
- examples/nlp/md/nl_image_search.md
- examples/nlp/nl_image_search.py
As a part of hugs keras sprint, this example was updated with model hub and space demo
NLP
- nl_image_search
> add space and model hub for nl_image_search example

- templates/keras_tuner/index.md
This fix the one I missed last time.
> Change `kt` to `keras_tuner` in imports

- examples/vision/deit.py
- examples/vision/ipynb/deit.ipynb
- examples/vision/md/deit.md
Added HF model & space for **examples/vision/deit** as a part of HF Keras sprint.
> Add HF model & space for DEIT

- scripts/autogen.py
updating keras-cv version to avoid docker-image check from failing
> updated keras-cv version

- templates/keras_cv/index.md
This is reflective of the API change being made in https://github.com/keras-team/keras-cv/pull/657
> Rename num_classes to classes for keras_cv landing page

- examples/vision/image_classification_efficientnet_fine_tuning.py
- examples/vision/ipynb/image_classification_efficientnet_fine_tuning.ipynb
- examples/vision/md/image_classification_efficientnet_fine_tuning.md
Put working link for efficientnet_weight_update_util.py at line 487
> Put working link for efficientnet_weight_update_util.py

- examples/vision/ipynb/mixup.ipynb
- examples/vision/md/mixup.md
- examples/vision/mixup.py
Fixed Broken link for FashionMnist dataset  and few grammar mistakes.
> Fixed Broken link for FashionMnist dataset

- examples/vision/convmixer.py
- examples/vision/ipynb/convmixer.ipynb
- examples/vision/ipynb/cutmix.ipynb
- examples/vision/ipynb/token_learner.ipynb
- examples/vision/md/convmixer.md
- examples/vision/md/cutmix.md
- examples/vision/md/token_learner.md
- examples/vision/token_learner.py
the table was not rendered properly earlier. I have updated it.
> Updated the table with links to model and space for CutMix, ConvMixer, TokenLearner examples -  Keras huggingface sprint

- examples/vision/md/eanet.md
Fixed Broken link for Source of eanet.py at top of page
> Fixed Broken link for Source of eanet.py

- examples/audio/ipynb/wav2vec2_audiocls.ipynb
- examples/audio/md/wav2vec2_audiocls.md
- examples/audio/wav2vec2_audiocls.py
This code example shows how to fine-tune Wav2Vec 2.0 on the Keyword Spotting task using Hugging Face Transformers. Additionally, it also shows best practices for Hugging Face Datasets.
> New Code Example: Training Wav2Vec 2.0 on Keyword Spotting using Hugging Face Transformers

- examples/nlp/ipynb/summarization.ipynb
- examples/nlp/md/summarization.md
- examples/nlp/summarization.py
This code example shows how to fine-tune T5 on the abstraction summarization task using Hugging Face Transformers. Additionally, it also shows best practices for Hugging Face Datasets.
> New Code Example: Training T5 on abstractive summarization using Hugging Face Transformers

- .gitignore
- examples/vision/adamatch.py
- examples/vision/ipynb/adamatch.ipynb
- examples/vision/md/adamatch.md
A little import fix and I added Hugging Face model and space links.
> Add adamatch HF space and model

- requirements.txt
Also converted all newlines as there was a mix of Unix and Windows style newlines.
> Add matplotlib in requirements as it is used in many examples.

- examples/vision/ipynb/nerf.ipynb
- examples/vision/md/nerf.md
- examples/vision/nerf.py
Put working link for Pyimagesearch in nerf.py at line 755
> Put working link for Pyimagesearch in nerf.py

- guides/ipynb/keras_cv/coco_metrics.ipynb
- guides/ipynb/keras_cv/custom_image_augmentations.ipynb
- guides/ipynb/keras_cv/cut_mix_mix_up_and_rand_augment.ipynb
- guides/ipynb/keras_cv/generate_images_with_stable_diffusion.ipynb
- guides/ipynb/keras_cv/retina_net_overview.ipynb
- guides/keras_cv/coco_metrics.py
- guides/keras_cv/custom_image_augmentations.py
- guides/keras_cv/cut_mix_mix_up_and_rand_augment.py
- guides/keras_cv/generate_images_with_stable_diffusion.py
- guides/keras_cv/retina_net_overview.py
- guides/md/keras_cv/coco_metrics.md
- guides/md/keras_cv/custom_image_augmentations.md
- guides/md/keras_cv/cut_mix_mix_up_and_rand_augment.md
- guides/md/keras_cv/generate_images_with_stable_diffusion.md
- guides/md/keras_cv/retina_net_overview.md
I'd like to move all of my links to twitter; its a good way to get in touch with users.
I don't think people find the twitter link from my personal site.
> Update [lukewood] personal links to twitter

- examples/generative/ipynb/random_walks_with_stable_diffusion.ipynb
- examples/generative/md/random_walks_with_stable_diffusion.md
- examples/generative/random_walks_with_stable_diffusion.py
Panda to plane I had to downscale to a factor of 0.5
The other two I downscaled to 0.7, as they weren't as big.
> Update gif links for SD random walks example

- guides/intro_to_keras_for_engineers.py
- guides/ipynb/intro_to_keras_for_engineers.ipynb
- templates/getting_started/intro_to_keras_for_engineers.md
There was an extra parenthesis present "Finding the best model configuration with hyperparameter tuning" section of in "Introduction to Keras for Engineers" which led to the piece of code not executing. Just removed that error which was coming due to an extra parenthesis. The changes have been made to all the files ( ".py, .md and .ipynb").
Signed off
Aman
Tagging the maintainer for review @fchollet
> Fixing the documentation

- guides/keras_nlp/transformer_pretraining.py
Output dictionary names changed in https://github.com/keras-team/keras-nlp/pull/327, but guide never updated
TESTED=ran guide locally
> Update "tokens" -> "token_ids"

- guides/keras_nlp/transformer_pretraining.py
Reverts keras-team/keras-io#1152
We don't actually want to ship this until we release KerasNLP 0.4 to pip.
> Revert "Update "tokens" -> "token_ids""

- examples/vision/edsr.py
- examples/vision/ipynb/edsr.ipynb
- examples/vision/md/edsr.md
Fixes broken link in edsr.py.
Patch Clone of #1101 .
> Fixes broken link in edsr.py

- templates/getting_started/ecosystem.md
- templates/keras_nlp/index.md
Closes https://github.com/keras-team/keras-nlp/issues/502.
> Update keras-nlp landing page for 0.4 release

- examples/generative/ddim.py
- examples/generative/ipynb/ddim.ipynb
- examples/generative/md/ddim.md
Minor typo correction in generative example DDIM.
> Suggestion for minor typo correction

- examples/vision/ipynb/oxford_pets_image_segmentation.ipynb
- examples/vision/md/oxford_pets_image_segmentation.md
- examples/vision/oxford_pets_image_segmentation.py
Updated the download URL for the Oxford Pets dataset
Signed-off-by: Kevin Coakley <kcoakley@sdsc.edu>
> Updated the URL for the Oxford Pets dataset

- guides/ipynb/keras_tuner/tailor_the_search_space.ipynb
- guides/keras_tuner/tailor_the_search_space.py
- guides/md/keras_tuner/tailor_the_search_space.md
- scripts/autogen.py
Do not merge until the KerasTuner release 1.2.0.
I will come back to this and generate the files.
> Bug fix for KerasTuner tutorial

- examples/structured_data/deep_neural_decision_forests.py
- examples/structured_data/ipynb/deep_neural_decision_forests.ipynb
- examples/structured_data/md/deep_neural_decision_forests.md
I am a part of Keras Working Group at HuggingFace. I have added the space and model for Deep Neural Decision Forest.
> Add Hugging Face Hub model and Space

- examples/vision/focal_modulation_network.py
- examples/vision/ipynb/focal_modulation_network.ipynb
- examples/vision/md/focal_modulation_network.md
> Typo in Focal Modulation Network notebook

- examples/nlp/ipynb/t5_hf_summarization.ipynb
- examples/nlp/md/t5_hf_summarization.md
- examples/nlp/t5_hf_summarization.py
I found more mistakes in this article while reading it the first time, but couldn't find them again while correcting it.
> Corrected a spelling mistake.

- Dockerfile
- requirements.txt
- scripts/autogen.py
- scripts/kt_api_master.py
> add the KerasTuner missing docs

- examples/generative/ipynb/text_generation_gpt.ipynb
- examples/generative/md/text_generation_gpt.md
- examples/generative/text_generation_gpt.py
- requirements.txt
- scripts/nlp_api_master.py
- templates/keras_nlp/index.md
This won't actually generate properly till I cut the 0.4.1 release on pypi, but opening for comments.
> Updates API and landing page for KerasNLP 0.4.1

- scripts/kt_api_master.py
Checked the generated websited. Everything looks good.
> Add keras_tuner.errors docs

- guides/ipynb/keras_cv/generate_images_with_stable_diffusion.ipynb
- guides/keras_cv/generate_images_with_stable_diffusion.py
- guides/md/keras_cv/generate_images_with_stable_diffusion.md
fix misspelling neglible -> negligible.
Wonderful KerasCV Stable Diffusion tutorial by the way! 👍
> fix a minor typo

- guides/ipynb/keras_nlp/getting_started.ipynb
- guides/keras_nlp/getting_started.py
- guides/md/keras_nlp/getting_started.md
Please check if the new link to pretraining guide is correct.
The old one is broken.
Do not merge before regenerating the md and ipynb files.
> Fixing typos in Keras-NLP getting started guide

- guides/md/intro_to_keras_for_engineers.md
Fixed the broken link for **Text classification**,  **Image classification** and **Credit card fraud detection**
> Fixed the broken link in intro_to_keras_for_engineers.md

- examples/generative/ipynb/cyclegan.ipynb
The Code was failing with **filepath=checkpoint_filepath\n"**, So it changed to **filepath=checkpoint_filepath,\n"** at line 755
> Fixing the code in cyclegan.ipynb

- examples/generative/dreambooth.py
- examples/generative/finetune_stable_diffusion.py
- examples/generative/ipynb/dreambooth.ipynb
- examples/generative/ipynb/finetune_stable_diffusion.ipynb
- examples/generative/md/dreambooth.md
- examples/generative/md/finetune_stable_diffusion.md
- guides/ipynb/keras_cv/retina_net_overview.ipynb
- guides/ipynb/keras_cv/simsiam_with_kerascv.ipynb
- guides/keras_cv/retina_net_overview.py
- guides/keras_cv/simsiam_with_kerascv.py
- guides/md/keras_cv/retina_net_overview.md
- guides/md/keras_cv/simsiam_with_kerascv.md
- requirements.txt
- scripts/autogen.py
- templates/keras_cv/index.md
Change all usages of `keras_cv.layers.Augmenter` to `keras.Sequential`.
This is the first step of https://github.com/keras-team/keras-cv/issues/1548 .
Also updated the KerasCV version to 0.4.2
> Change all usages of Augmenter to Sequential

- guides/md/sequential_model.md
Fixed the broken link for Guide to the Functional API in line 543 & Guide to making new Layers & Models via subclassing in line 544
> Fixed the broken link in sequential_model.md

- examples/audio/ipynb/wav2vec2_audiocls.ipynb
- examples/audio/md/wav2vec2_audiocls.md
- examples/audio/wav2vec2_audiocls.py
- examples/nlp/active_learning_review_classification.py
- examples/nlp/ipynb/active_learning_review_classification.ipynb
- examples/nlp/md/active_learning_review_classification.md
- examples/vision/adamatch.py
- examples/vision/ipynb/adamatch.ipynb
- examples/vision/md/adamatch.md
fixed typos - 'contratsive', 'reprentations', 'uncertanity', 'appearence' in .ipynb, .py and .md files
> fixed typos - 'contratsive', 'reprentations', 'uncertanity', 'appearence' :)

- guides/ipynb/keras_nlp/transformer_pretraining.ipynb
- guides/keras_nlp/transformer_pretraining.py
- guides/md/keras_nlp/transformer_pretraining.md
Initial in capitalization. Markdown and Notebook version included.
> style: reduce typo KerasNLP Transformer

- guides/ipynb/keras_cv/object_detection_keras_cv.ipynb
- guides/keras_cv/object_detection_keras_cv.py
- guides/md/keras_cv/object_detection_keras_cv.md
I'll re-render sometime next week.
> Cherry pick changes to OD guide

- templates/keras_nlp/index.md
> Update links on keras-nlp home page

- examples/nlp/ipynb/neural_machine_translation_with_keras_nlp.ipynb
- examples/nlp/md/neural_machine_translation_with_keras_nlp.md
- examples/nlp/neural_machine_translation_with_keras_nlp.py
Replaces old `keras_nlp.utils.xx_search` API with `keras_nlp.samplers`.
> Update the KerasNLP translation example for keras-nlp 0.5.x

- examples/generative/ipynb/text_generation_gpt.ipynb
- examples/generative/md/text_generation_gpt.md
- examples/generative/text_generation_gpt.py
Replaces old `keras_nlp.utils.xx_search` API with `keras_nlp.samplers`.
> Update the "GPT from scratch" example for keras-nlp 0.5.x

- examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb
- examples/nlp/md/neural_machine_translation_with_transformer.md
- examples/nlp/neural_machine_translation_with_transformer.py
https://github.com/keras-team/keras-io/pull/1254 This PR wrongly stated the year as 2022 instead of 2023 upon the last modification.
> last modified date fix, machine translation example

- examples/vision/learnable_resizer.py
- examples/vision/metric_learning_tf_similarity.py
- examples/vision/patch_convnet.py
The typos in different files were fixed.
> Modified the typos

- examples/nlp/ipynb/mlm_training_tpus.ipynb
- examples/nlp/md/mlm_training_tpus.md
- examples/nlp/mlm_training_tpus.py
Colab Notebook: 
https://colab.research.google.com/drive/1wHz14lg93dmGsMu_RZoUWFwdVxBWX9Xe?usp=sharing
Cc: @RocketKnight1
> add: example on training mlms from scratch on tpus.

- examples/nlp/ipynb/text_classification_from_scratch.ipynb
- examples/nlp/md/text_classification_from_scratch.md
- examples/nlp/text_classification_from_scratch.py
Renamed 'vocab layer' to 'vectorize_layer' in code comments
> Renamed 'vocab layer' to 'vectorize_layer' in comments

- examples/vision/ipynb/oxford_pets_image_segmentation.ipynb
- examples/vision/md/oxford_pets_image_segmentation.md
- examples/vision/oxford_pets_image_segmentation.py
> Remove extra activation layer

- guides/ipynb/keras_nlp/getting_started.ipynb
- guides/keras_nlp/getting_started.py
- guides/md/keras_nlp/getting_started.md
We need `num_classes=2` with `preprocessor=None`, otherwise it would throw error.
> fixing getting started guide kerasnlp

- templates/keras_core/index.md
- templates/keras_cv/index.md
- templates/keras_nlp/index.md
Landing pages now match Github READMEs
> Update Keras ecosystem docs for Keras Core

- examples/vision/image_classification_efficientnet_fine_tuning.py
- examples/vision/ipynb/image_classification_efficientnet_fine_tuning.ipynb
- examples/vision/md/image_classification_efficientnet_fine_tuning.md
Closes: https://github.com/keras-team/keras-io/issues/379
> Fix typo from NUM_CLASSES to num_classes

- examples/vision/ipynb/retinanet.ipynb
- examples/vision/md/retinanet.md
- examples/vision/retinanet.py
Change optimizer to legacy optimizer to restore the checkpoints from legacy optimizer.
Gist: https://gist.github.com/sachinprasadhs/1f6e4c79c128c1aa59e2bb0dbf19e0cf
> Change optimizer to legacy optimizer

- guides/md/making_new_layers_and_models_via_subclassing.md
Fixed the broken link in **making_new_layers_and_models_via_subclassing.md** for the `Serialization`
> Fixed the broken link in making_new_layers_and_models_via_subclassing.md

- templates/api/keras_nlp/models/index.md
First content link here: https://keras.io/api/keras_nlp/models/
> fixed internal link

- templates/getting_started/intro_to_keras_for_engineers.md
- templates/getting_started/intro_to_keras_for_researchers.md
- templates/keras_core/guides/distributed_training_with_jax.md
- templates/keras_core/guides/distributed_training_with_torch.md
It looks like we made some changes to example source files and added some examples without building them. This PR should fix that.
> Leftover changes

- guides/ipynb/keras_tuner/getting_started.ipynb
- guides/keras_tuner/getting_started.py
- guides/md/keras_tuner/getting_started.md
- guides/working_with_rnns.py
Updated a few typos in documentation. Also fixing #1038
> Corrected minor typos

- examples/generative/ipynb/wgan_gp.ipynb
- examples/generative/md/wgan_gp.md
- examples/generative/wgan_gp.py
Change random.normal to random.uniform for alpha as per the research paper.
Closes: https://github.com/keras-team/keras-io/issues/415
> Change random.normal to random.uniform

- examples/nlp/ipynb/text_classification_with_switch_transformer.ipynb
- examples/nlp/md/text_classification_with_switch_transformer.md
- examples/nlp/text_classification_with_switch_transformer.py
This PR should fix this failed CI test: https://github.com/pcoet/keras-io/actions/runs/5861937300
> fix formatting issue with example

- templates/keras_nlp/index.md
Forgot to sync a change to keras.io landing page!
> Update KerasNLP quickstart example

- scripts/guides_master.py
This PR adds the advanced saving tutorial to `guides_master.py` to allow for rendering on keras.io.
> Update guides_master.py for advanced saving tutorial

- examples/vision/ipynb/near_dup_search.ipynb
- examples/vision/md/near_dup_search.md
- examples/vision/near_dup_search.py
Updated broken pre-trained model link and included tensorrt setup.
> Update broken pre-trained model link

- examples/vision/ipynb/video_classification.ipynb
- examples/vision/md/video_classification.md
- examples/vision/video_classification.py
Updated broken dataset link and change deprecated argument for `imageio.mimsave` from fps to duration.
10 fps = 1000 ms /10 fps == 100 ms
Attached working Gist: https://gist.github.com/sachinprasadhs/07251daafce6a898443ba42292ffa98f
cc: @sayakpaul
> Update broken dataset link

- guides/intro_to_keras_for_researchers.py
- guides/training_with_built_in_methods.py
- guides/writing_a_training_loop_from_scratch.py
Use the mean (not the sum) of input-dependent losses, matching PR https://github.com/keras-team/keras-io/pull/1144.
> Align guides with docstring of Layer.add_loss():

- guides/ipynb/keras_nlp/transformer_pretraining.ipynb
- guides/keras_nlp/transformer_pretraining.py
- guides/md/keras_nlp/transformer_pretraining.md
Removed multiple concurrent occurrence of keyword **our**
> Minor typo fix

- contributor_guide.md
> Fixed typo in contributor_guide.md

- scripts/autogen.py
Update KerasTuner to 1.4.5 release
> Update KerasTuner to 1.4.5 release

- examples/generative/dreambooth.py
- examples/generative/ipynb/dreambooth.ipynb
- examples/generative/md/dreambooth.md
Update ImageEncoder args and downgrade `keras-cv` version to 0.6.0 to fix the import error.
> Update ImageEncoder args

- examples/structured_data/imbalanced_classification.py
- examples/structured_data/ipynb/imbalanced_classification.ipynb
- examples/structured_data/md/imbalanced_classification.md
Marked as tf only for some reason, but this is actually all backends
> Keras 3 imbalanced classification

- examples/generative/ipynb/lstm_character_level_text_generation.ipynb
- examples/generative/lstm_character_level_text_generation.py
- examples/generative/md/lstm_character_level_text_generation.md
Should work for any backend ran it on JAX
> Character level LSTM generation

- guides/ipynb/keras_nlp/transformer_pretraining.ipynb
- guides/keras_nlp/transformer_pretraining.py
- guides/md/keras_nlp/transformer_pretraining.md
Only minor fixes here, was already updated to keras-core a bit ago
> Re-render transformer pretraining for keras 3

- examples/nlp/ipynb/neural_machine_translation_with_keras_nlp.ipynb
- examples/nlp/md/neural_machine_translation_with_keras_nlp.md
- examples/nlp/neural_machine_translation_with_keras_nlp.py
Looks like this was already ported, so just adding the pip install line in keeping with other examples.
> Add install line for neural_machine_translation_with_keras_nlp

- examples/nlp/data_parallel_training_with_keras_nlp.py
- examples/nlp/ipynb/data_parallel_training_with_keras_nlp.ipynb
- examples/nlp/md/data_parallel_training_with_keras_nlp.md
- scripts/examples_master.py
- templates/keras_nlp/index.md
Changing the title so this is clear this is for tf.distribute
> Port data parallel training with KerasNLP to Keras 3

- guides/sequential_model.py
Fixed broken links from the documents from /keras/guides to /guides
> Fix broken links

- scripts/api_master.py
Might need https://github.com/keras-team/keras-io/pull/1655
> Bring back KerasCV and KerasNLP API sections

- Dockerfile
- README.md
- requirements.txt
- scripts/autogen.py
* Move `keras 3` from requirements.txt to Dockerfile.  `pip` will not update it since it fails validation for TensorFlow.
* Update KerasNLP, CV, Tuner to latest version that also fully support Keras 3.
The conflicts in requirements were causing out of space issue in Github Action since multiple copies of TF were downloaded due to conflicts - 
```
#8 101.4 Collecting tensorflow
#8 101.4   Downloading tensorflow-2.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (578.1 MB)
#8 109.6      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 578.1/578.1 MB 3.0 MB/s eta 0:00:00
#8 110.2   Downloading tensorflow-2.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.8 MB)
#8 117.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 MB 3.7 MB/s eta 0:00:00
#8 117.9 Collecting …
```
> Update requirements for Keras 3

- examples/vision/ipynb/nnclr.ipynb
- examples/vision/md/nnclr.md
- examples/vision/nnclr.py
Reverts keras-team/keras-io#1730
> Revert "Migrating Nnclr to Keras-3[TF BackEnd]"

- guides/md/preprocessing_layers.md
I believe this has been fixed for awhile - maybe instead we can update the message just to indicate that it was 
(feel free to reject/close PR if this is intentionally here for notekeeping)
> Remove potentially outdated warning about TPU performance degredation

- examples/vision/ipynb/semisupervised_simclr.ipynb
- examples/vision/md/semisupervised_simclr.md
- examples/vision/semisupervised_simclr.py
Fixed the broken links  of `RandomTranslation` and `RandomZoom` Layers in **semisupervised_simclr.py**
> Fixed the broken links in semisupervised_simclr.py

- examples/nlp/ipynb/text_classification_with_transformer.ipynb
- examples/nlp/md/text_classification_with_transformer.md
- examples/nlp/text_classification_with_transformer.py
This PR changes the [Text classification with Transformer](https://keras.io/examples/nlp/text_classification_with_transformer/) example to keras 3.0 [All Backend].
https://colab.research.google.com/drive/1EnnbWbx6eFAWe5NySES-HLtChMx1bSvT?usp=sharing
cc: @divyashreepathihalli @fchollet 
```
diff --git a/examples/nlp/text_classification_with_transformer.py b/examples/nlp/text_classification_with_transformer.py
index 165f7fe7..7e021ab8 100644
--- a/examples/nlp/text_classification_with_transformer.py
+++ b/examples/nlp/text_classification_with_transformer.py
@@ -10,9 +10,9 @@ Accelerator: GPU
"""
-import tensorflow as tf
-from tensorflow …
```
> Migrating Text classification with Transformer example to Keras 3

- examples/vision/ipynb/xray_classification_with_tpus.ipynb
- examples/vision/md/xray_classification_with_tpus.md
- examples/vision/xray_classification_with_tpus.py
This example is tf specific as it uses `tf.distribute` to handle the TPU's.
> Update x-ray example to version 3

- examples/vision/handwriting_recognition.py
- examples/vision/ipynb/handwriting_recognition.ipynb
- examples/vision/md/handwriting_recognition.md
Fixed the broken link of `Pre-processing` in **handwriting_recognition.py**
> Fixed the broken link in handwriting_recognition.py

- scripts/examples_master.py
Mark semantic image clustering as Keras 3
> Mark semantic image clustering as Keras 3

- .github/workflows/csat.yaml
- .github/workflows/scripts/constant.js
- .github/workflows/scripts/csat.js
- .github/workflows/scripts/stale_csat.js
- .github/workflows/stale-issues-pr.yml
Closing an issue tagged with a designated label automatically triggers the posting of a CSAT survey.
> For issues with certain labels, closing triggers a CSAT survey comment.

- examples/vision/xray_classification_with_tpus.py
At the moment on my other pull request I was seeing a formatting failure for this unrelated file
I ran black on it and am just sending it in
> Fixing black formatting issues in xray_classification_with_tpus.py 

- scripts/api_master.py
Still some saving APIs that I wasn't sure where to add but they can be a part of a second round. 
Unclear on the actual process to generate the site once we update API_MASTER.
> Update API master with new APIs

- examples/structured_data/feature_space_advanced.py
Fixed the broken link of **Pre-processing** in `feature_space_advanced.py`
> Fixed the broken link in feature_space_advanced.py

- examples/graph/gat_node_classification.py
- examples/graph/gnn_citations.py
- examples/graph/ipynb/gat_node_classification.ipynb
- examples/graph/ipynb/gnn_citations.ipynb
- examples/graph/ipynb/mpnn-molecular-graphs.ipynb
- examples/graph/ipynb/node2vec_movielens.ipynb
- examples/graph/md/gat_node_classification.md
- examples/graph/md/gnn_citations.md
- examples/graph/md/mpnn-molecular-graphs.md
- examples/graph/md/node2vec_movielens.md
- examples/graph/mpnn-molecular-graphs.py
- examples/graph/node2vec_movielens.py
- examples/keras_recipes/approximating_non_function_mappings.py
- examples/keras_recipes/better_knowledge_distillation.py
- examples/keras_recipes/ipynb/approximating_non_function_mappings.ipynb
- examples/keras_recipes/ipynb/better_knowledge_distillation.ipynb
- examples/keras_recipes/ipynb/packaging_keras_models_for_wide_distribution.ipynb
- examples/keras_recipes/ipynb/sample_size_estimate.ipynb
- examples/keras_recipes/ipynb/tf_serving.ipynb
- examples/keras_recipes/md/approximating_non_function_mappings.md
- examples/keras_recipes/md/better_knowledge_distillation.md
- examples/keras_recipes/md/packaging_keras_models_for_wide_distribution.md
- examples/keras_recipes/md/sample_size_estimate.md
- examples/keras_recipes/md/tf_serving.md
- examples/keras_recipes/packaging_keras_models_for_wide_distribution.py
- examples/keras_recipes/sample_size_estimate.py
- examples/keras_recipes/tf_serving.py
Fixed typos in examples/graph & examples/keras_recipes.
> Fixed typos in examples/graph & examples/keras_recipes.

- scripts/autogen.py
> Fix CI: update tf_keras to 2.16

- scripts/master.py
- templates/getting_started/benchmark.md
> add benchmarks

- scripts/autogen.py
- templates/getting_started/index.md
Update Getting Started for TF 2.16
> Update Getting Started for TF 2.16

- examples/keras_recipes/ipynb/trainer_pattern.ipynb
- examples/keras_recipes/md/trainer_pattern.md
- examples/keras_recipes/trainer_pattern.py
> fix broken url in trainer_pattern.py

- examples/nlp/active_learning_review_classification.py
- examples/nlp/data_parallel_training_with_keras_nlp.py
- examples/nlp/ipynb/active_learning_review_classification.ipynb
- examples/nlp/ipynb/data_parallel_training_with_keras_nlp.ipynb
- examples/nlp/ipynb/masked_language_modeling.ipynb
- examples/nlp/ipynb/multiple_choice_task_with_transfer_learning.ipynb
- examples/nlp/ipynb/pretraining_BERT.ipynb
- examples/nlp/ipynb/semantic_similarity_with_bert.ipynb
- examples/nlp/ipynb/t5_hf_summarization.ipynb
- examples/nlp/ipynb/text_classification_with_switch_transformer.ipynb
- examples/nlp/ipynb/text_classification_with_transformer.ipynb
- examples/nlp/ipynb/tweet-classification-using-tfdf.ipynb
- examples/nlp/masked_language_modeling.py
- examples/nlp/md/active_learning_review_classification.md
- examples/nlp/md/data_parallel_training_with_keras_nlp.md
- examples/nlp/md/masked_language_modeling.md
- examples/nlp/md/multiple_choice_task_with_transfer_learning.md
- examples/nlp/md/pretraining_BERT.md
- examples/nlp/md/semantic_similarity_with_bert.md
- examples/nlp/md/t5_hf_summarization.md
- examples/nlp/md/text_classification_with_switch_transformer.md
- examples/nlp/md/text_classification_with_transformer.md
- examples/nlp/md/tweet-classification-using-tfdf.md
- examples/nlp/multiple_choice_task_with_transfer_learning.py
- examples/nlp/pretraining_BERT.py
- examples/nlp/semantic_similarity_with_bert.py
- examples/nlp/t5_hf_summarization.py
- examples/nlp/text_classification_with_switch_transformer.py
- examples/nlp/text_classification_with_transformer.py
- examples/nlp/tweet-classification-using-tfdf.py
> Fixed types in nlp examples

- requirements.txt
- scripts/autogen.py
- scripts/nlp_api_master.py
- scripts/render_tags.py
Still a draft until we actually publish the release.
> Update keras.io for KerasNLP 0.9.1

- examples/generative/gpt2_text_generation_with_kerasnlp.py
- examples/generative/ipynb/gpt2_text_generation_with_kerasnlp.ipynb
- examples/generative/md/gpt2_text_generation_with_kerasnlp.md
This PR fixes some docs issues for the [GPT2 Text Generation with KerasNLP](https://keras.io/examples/generative/gpt2_text_generation_with_kerasnlp/) example.
cc: @fchollet
```
diff --git a/examples/generative/gpt2_text_generation_with_kerasnlp.py b/examples/generative/gpt2_text_generation_with_kerasnlp.py
index 6b3eeb73..5cab89e1 100644
--- a/examples/generative/gpt2_text_generation_with_kerasnlp.py
+++ b/examples/generative/gpt2_text_generation_with_kerasnlp.py
@@ -1,8 +1,8 @@
"""
Title: GPT2 Text Generation with KerasNLP
Author: Chen Qian
-Date created: 04/17/2023
-Last modified: 04/17/2023
+Date created: 2023/04/17
+Last modified: 2024/04/12
Description: Use KerasNLP GPT2 model and …
```
> Docs-fix for GPT2 Text Generation with KerasNLP example

- examples/structured_data/ipynb/tabtransformer.ipynb
- examples/structured_data/tabtransformer.py
Fix notebook render issue due to invalid JSON format and unable to load the notebook which was created due to extra empty line.
Making the changes on behalf of user PR here https://github.com/keras-team/keras-io/pull/1834 since he can't sign CLA.
> Fix notebook render issue

- guides/md/customizing_what_happens_in_fit.md
- guides/md/distributed_training.md
- guides/md/preprocessing_layers.md
- guides/md/working_with_rnns.md
- guides/md/writing_a_training_loop_from_scratch.md
**PR Summary**:
Commit 855e37d4f5562751e6694cdadf93b2b7a72c935f changed the location of different Python scripts. This PR adjusts sources to changes.
> Update the pointers to python scripts

- guides/migrating_to_keras_3.py
- scripts/api_master.py
Also add pad and crop images to the migration guide.
> [Docs] Add crop images to API doc.

- examples/vision/captcha_ocr.py
- examples/vision/ipynb/captcha_ocr.ipynb
- examples/vision/md/captcha_ocr.md
`tf.keras.random.shuffle` returns random elements and does not apply in-place
> BUGFIX: "indices" does not shuffling

- examples/keras_recipes/float8_training_and_inference_with_transformer.py
- examples/keras_recipes/ipynb/float8_training_and_inference_with_transformer.ipynb
- examples/keras_recipes/md/float8_training_and_inference_with_transformer.md
- scripts/autogen.py
Just a simple fix to better align the list more neatly
EDITED:
Fix `PROJECT_URL` for KerasNLP
> Fix markdown in float8 example

- scripts/autogen.py
> Update keras version

- scripts/autogen.py
Update tf_keras version to 2.17.0
> Update tf_keras version

- examples/structured_data/feature_space_advanced.py
- examples/structured_data/ipynb/feature_space_advanced.ipynb
- examples/structured_data/md/feature_space_advanced.md
Fixed the broken link of Pre-processing in feature_space_advanced
> Fixed the broken link in feature_space_advanced

- guides/ipynb/custom_train_step_in_tensorflow.ipynb
- guides/ipynb/customizing_what_happens_in_fit.ipynb
Fix the typo error in custom_train_step_in_tensorflow.ipynb
> Fix the typo error in custom_train_step_in_tensorflow.ipynb

- examples/nlp/ipynb/multi_label_classification.ipynb
- examples/nlp/md/multi_label_classification.md
- examples/nlp/multi_label_classification.py
Fixed the broken link of **Pre-processing** in multi_label_classification.py
> Fixed the broken link in multi_label_classification.py

- examples/structured_data/ipynb/collaborative_filtering_movielens.ipynb
Fix notebook rendering issue.
Fixes: https://github.com/keras-team/keras-io/issues/1917
[Before](https://github.com/keras-team/keras-io/blob/master/examples/structured_data/ipynb/collaborative_filtering_movielens.ipynb)
[After](https://github.com/keras-team/keras-io/blob/sachinprasadhs-patch-1/examples/structured_data/ipynb/collaborative_filtering_movielens.ipynb)
> Fix rendering issue

- examples/vision/ipynb/sam.ipynb
- examples/vision/md/sam.md
- examples/vision/sam.py
fix #1926
@merveenoyan @sayakpaul
> Fixed `Segment Anything Model with 🤗Transformers` notebook small issues

- scripts/autogen.py
- scripts/nlp_api_master.py
- templates/api/keras_nlp/models/index.md
We've made a number of name changes to accommodate multi-modal models with a lot more task types. Reworking the order of docs so that a task a task preprocesser are always paired next to each other.
> Bump KerasNLP version to 15.1 and update symbols

- examples/audio/ipynb/transformer_asr.ipynb
- examples/audio/md/transformer_asr.md
Linked to https://github.com/keras-team/keras-io/pull/1959#pullrequestreview-2380667523
> update path for windows

- examples/vision/basnet_segmentation.py
This PR changes the Highly accurate boundaries segmentation using BASNet to keras 3.0 (Tensorflow backend only), as requested in https://github.com/keras-team/keras-cv/issues/2211
Please review the attached [gist](https://colab.sandbox.google.com/gist/chunduriv/27cd0f239d5184f88f1ca07a225059c0/basnet_segmentation.ipynb).
> Highly accurate boundaries segmentation using BASNet to keras 3.0 (Tensorflow backend only)

- scripts/hub_api_master.py
- templates/keras_hub/index.md
Update models details to hub_api
> Update models details to hub_api

- guides/ipynb/migrating_to_keras_3.ipynb
- guides/md/migrating_to_keras_3.md
- guides/migrating_to_keras_3.py
- scripts/autogen.py
> Fix migration guide update. Bump tf-keras to 2.18.0

- scripts/autogen.py
The slow part of rendering was compiling and running regexes for symbol -> link replacement.
Moving to string.replace instead of a regex is dramatically faster. I'm ditching the the `tf.keras.xx` link replacement as well, there's very few and we don't want to encourage that style of link anyway. So just `keras.xx` and `tf.xx` (goes to tf.org).
> Speed up site rendering by a factor of ~4

- examples/structured_data/md/customer_lifetime_value.md
Small PR - Commit 3ea573f0f124c7a3182aba904c53b521a52289cf moved `customer_lifetime_value.py`. This PR adjusts sources to changes.
> Update Customer Lifetime Value references

- examples/structured_data/ipynb/structured_data_classification_from_scratch.ipynb
- examples/structured_data/md/structured_data_classification_from_scratch.md
- examples/structured_data/structured_data_classification_from_scratch.py
Find PR for adopting the script `structured_data_classification_from_scratch.py` to be ***Backend-Agnostic***
> Adapting the script structured_data_classification_from_scratch.py to be Backend-Agnostic

- scripts/api_master.py
- I have added descriptions for newly added operations
```
keras.ops.image.perspective_transform
keras.ops.image.gaussian_blur
```
- I have added descriptions for newly added layers.
```
keras.layers.AugMix
keras.layers.CutMix
keras.layers.RandomInvert
keras.layers.RandomErasing
keras.layers.RandomGaussianBlur
keras.layers.RandomPerspective
```
> Add image layers description

- theme/base.html
- theme/keras_3.html
- theme/landing.html
We should ideally do this through a fancier hosting solution rather than this manual approach. But let's get this out to unbreak peoples pages.
> Cache bust css for keras.io

- guides/ipynb/keras_hub/getting_started.ipynb
- guides/keras_hub/getting_started.py
- guides/md/keras_hub/getting_started.md
We haven't needed this for months.
> Stop using nightly for KerasHub getting started

- scripts/autogen.py
- scripts/tutobooks.py
Added better detection of blocks that are progress bars.
Added better handling of progress bars to only display the final state of each progress bar.
> Fix progress bars in tutobooks.

- scripts/hub_master.py
Reverts keras-team/keras-io#2101
These symbols are not released in keras-hub and this is blocking CI.
> Revert " Add Mixtral,Qwen-Moe,Qwen,Xception API usage"

- scripts/api_master.py
- scripts/rs_master.py
Also remove spurious duplicate entry for `ModelParallel`.
> Add documentation for `DistributedEmbedding.preprocess`.

- requirements.txt
- scripts/autogen.py
- scripts/hub_master.py
Reverts keras-team/keras-io#2110
> Adding the reverted changes back from #2110

- scripts/hub_master.py
Add Load HuggingFace Transformers checkpoint into a multi backend KerasHub model which was added recently.
> add hugging face guide to hub

- .github/workflows/continuous_integration.yml
Update python version to fix the docker issue
> Update python version.

- requirements.txt
- scripts/autogen.py
- scripts/hub_master.py
- Update Keras Hub version
- Pin Tensorflow and TF-Keras version to avoid circular imports till we have matching TF-Keras version with TF.
- Updated DinoV2 API doc.
> Add DinoV2 and update Keras hub version

- examples/vision/handwriting_recognition.py
- examples/vision/ipynb/handwriting_recognition.ipynb
- examples/vision/md/handwriting_recognition.md
The Handwriting Recognition [Example](https://keras.io/examples/vision/handwriting_recognition/#model) had rendering issues due to missing backticks which caused the final image and the Final Remarks section to display incorrectly.
This fix adds the missing backticks  to resolve those layout problems
> Fix Markdown Rendering for Handwriting Recognition Example
