guides/distributed_training.py

The example already does a great job discussing different flavors of distributed training for Keras models. In the **Further reading** section, I just added a link to my article that shows the use of `MirroredStrategy` in a bit more detailed way.

Adding an example that shows MirroredStrategy

---

templates/about.md
templates/api/layers/constraints.md

The tf.keras imports appear to be missing in case of [templates/api/layers/constraints.md](https://github.com/keras-team/keras-io/blob/master/templates/api/layers/constraints.md). It has been fixed and tf.keras imports have been added replacing the old multi-backend keras imports.

[Constraints] Change to tf.keras import

---

templates/about.md

The tf.keras imports appear to be missing in case of [templates/about.md](https://github.com/keras-team/keras-io/blob/master/templates/about.md). It has been fixed and tf.keras imports have been added replacing the old multi-backend keras imports.

[About keras] Change to tf.keras import

---

templates/api/applications/index.md

The tf.keras imports appear to be missing in case of [templates/api/applications/index.md](https://github.com/keras-team/keras-io/blob/master/templates/api/applications/index.md). It has been fixed and tf.keras imports have been added replacing the old multi-backend keras imports.

[Keras Applications] Change to tf.keras import

---

.github/workflows/continuous_integration.yml
examples/vision/image_classification_from_scratch.py

This is the start of our CI system. Let's start small.
The CI will start running automatically for the first time once this is merged in master. It's a security in github actions. Github actions isn't enabled unless the first workflow file is committed to the repo.
It's possible to see the result of the CI on my fork: https://github.com/gabrieldemarmiesse/keras-io/pull/2

Added minimal CI with a black check

---

examples/nlp/ipynb/text_classification_with_transformer.ipynb
examples/nlp/md/text_classification_with_transformer.md
examples/nlp/text_classification_with_transformer.py

The example shows how to implement a transformer block as a Keras layer and use it for text classification on IMDB data. 
The model trains faster than an LSTM based classifier with a similar number of parameters and gives slightly better results.
- The transformer shown in the example is a small one; 2 attention heads, and small dimensions for projection heads and FFN. It achieves validation accuracy of 87% on IMDB in less than a minute on CPU.
- There is not a whole lot of description about the multi-head self-attention part, as I feel like that would make this into a detailed tutorial. Just implemented a simple version of the transformer block which can be used in place of an LSTM or GRU layer.  
(More description can be added if the maintainers feel like it is needed)
- Positional …

Added transformer example

---

templates/getting_started/intro_to_keras_for_engineers.md

Fixed typos on the template. 
However, **I wasn't able to run the autogen** to generate all the typo fixes on all the versions.
Does the newly introduced CI do that? If so, we need to change the documentation on autogeneration as well.

Fix typos on intro to keras for engineers

---

examples/vision/oxford_pets_image_segmentation.py

When segmenting multi-class images, we expect a pixel to be assigned with one label from the num_classes. Therefore, the last activation must be "softmax", especially when compiling with "categorical_crossentropy" loss

activation of num_classes > 1 should be softmax

---

guides/working_with_rnns.py

The links to keras documentation of LSTM, GRU, and bidirectional recurrent layers were broken.

Fixed broken links to keras api in Working with RNNs developer guide

---

guides/distributed_training.py
guides/ipynb/distributed_training.ipynb
guides/md/distributed_training.md

In the distributed training guide,  line [367](https://github.com/keras-team/keras-io/blob/6e6ffd12e95c068f0290c9589aa1d6ce721fcb64/guides/distributed_training.py#L367), it should be `since it runs on a single machine and does **not** need to communicate with other machines` instead of `since it runs on a single machine and does need to communicate with other machines`

Fix a typo in Multi-GPU guide

---

templates/about.md

Minor update to indicate support for python3.8 in TF2.2:
https://pypi.org/project/tensorflow/2.2.0/#files

Add Keras compatibility for py38

---

examples/rl/deep_q_network_breakout.py
examples/rl/ipynb/deep_q_network_breakout.ipynb

Issue #82 
Adding baselines package need to run the notebook,
Correcting small typo
Changing huber loss function for tf2

DQN example huber loss and typo, issue #82

---

scripts/autogen.py

allow_reuse_address should be set for the class because it's class variable.
Please check https://docs.python.org/3.7/library/socketserver.html#socketserver.BaseServer.allow_reuse_address 
Thanks

Fix allow_reuse_address usage

---

examples/rl/deep_q_network_breakout.py
examples/rl/ipynb/deep_q_network_breakout.ipynb
examples/rl/md/deep_q_network_breakout.md

DQN keeps two copies of the weights (a normal Q model for exploration and a target model for computing the target Q values during training).
The code before this pull-request didn't create the two copies **properly**. Instead, the Q model and the target model always shared the same weights.
+ some minor fixes (instantiation of the Huber loss, variable *update_target_network* not used)

Bugfix: Q model and target model used the same weights

---

scripts/master.py

This PR removes the duplication of the link to ExponentialDecay from [here](https://keras.io/api/optimizers/learning_rate_schedules/).
Duplication in code can be found on [line149](https://github.com/keras-team/keras-io/blob/master/scripts/master.py#L149) and [line169](https://github.com/keras-team/keras-io/blob/master/scripts/master.py#L169).

Removes duplication of ExponentialDecay from list

---

examples/generative/vae.py

They are attributes of the `VAE` class.

Update vae.py: do not use global encoder and decoder

---

.github/workflows/continuous_integration.yml
Dockerfile
Makefile
README.md

Previously in CI implementation we're using only docker build and docker run
to perform e2e test, yet we still need to make sure the test performed for this
is more elaborate by providing a command to do that.
Related to https://github.com/keras-team/keras-io/issues/14

test: Add makefile to ensure testing using container can be performed even in local

---

guides/functional_api.py

Fixes typos in functional_api.py

Fixes typos in docs

---

guides/serialization_and_saving.py

From: 
"The Keras API makes it possible to save of these pieces to disk at once,
or to only selectively save some of them:"
To:
"The Keras API makes it possible to save all of these pieces to disk at once,
or to only selectively save some of them:"

Fixed typo in introduction.

---

requirements.txt

2.2 is no longer available.  Using [compatible release clause](https://www.python.org/dev/peps/pep-0440/#compatible-release) `~=` will allow pip to find the latest 2.3 nightly.
See https://github.com/keras-team/keras-io/issues/149#issuecomment-659465308

Update tf-nightly requirement to 2.3

---

guides/intro_to_keras_for_engineers.py

Instead of listing it as "learn about:" and then starting each point with "How to", it would be more readable starting each point with keywords such as "Prepare, Build" etc. This draws more attention from the reader.

Made "Introduction" more readable

---

guides/intro_to_keras_for_researchers.py

```
accuracy.reset_states()
```
should be
```
accuracy.reset_states()
```
Thanks

Fix a typo in intro_to_keras_for_researchers

---

examples/generative/vae.py

removed `+1` from end_range so pixel_range has the same shape as sample_range_x (array of 30 elements).

fixed display of ticks in `plot_latent`.

---

templates/api/losses/index.md

At Line 42, correct spelling error from "sparse_categorical_crossenropy" to "sparse_categorical_crossentropy"

Correct typo

---

guides/ipynb/training_keras_models_on_cloud.ipynb
guides/md/training_keras_models_on_cloud.md
guides/training_keras_models_on_cloud.py

The run() call, model.load(), and tensorboard log generation have all been temporarily commented out to allow the successful creation of a notebook. I'll manually add these in after generation.

Add TensorFlow Cloud guide to keras.io

---

guides/ipynb/training_keras_models_on_cloud.ipynb
guides/md/training_keras_models_on_cloud.md
guides/training_keras_models_on_cloud.py

There might be some manual merging necessary due to your link update, but it should be straightforward.

Fix typos and reformat markdown for Cloud guide

---

scripts/autogen.py

- commands add_guides & generate_tf_guides are not mentioned when command is not found

made mistype erros more verbose in autogen.py

---

scripts/autogen.py

On Windows 10, new conda environment with python 3.7 `python autogen.py make` gave 2 errors similar to #100 
```
File "autogen.py", line 86, in make_examples_master
f.readline()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x91 in position 7775: illegal multibyte sequence
File "autogen.py", line 558, in render_md_sources_to_html
md_content = md_file.read()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x93 in position 5643: illegal multibyte sequence
```
Fixed by adding `encoding="utf-8"` to the file open statements. Hopefully this is useful for other contributors too.
Signed-off-by: Robert Altena <Rob@Ra-ai.com>

fix autogen.py make for win10.

---

guides/ipynb/preprocessing_layers.ipynb
guides/md/preprocessing_layers.md
guides/preprocessing_layers.py
tf/preprocessing_layers.ipynb

See the [right side TOC](https://www.tensorflow.org/guide/keras/preprocessing_layers), everything under "quick recipes" should be H3s.
```
python autogen.py generate_tf_guides preprocessing_layers.py
python autogen.py add_guide preprocessing_layers.py
```

Normalize headings in preprocessing guide.

---

guides/ipynb/preprocessing_layers.ipynb
guides/md/preprocessing_layers.md
guides/preprocessing_layers.py
tf/preprocessing_layers.ipynb

Show the encoded text in the last two examples of the preprocessing guide.
Requested by @yashk2810 
Regenerated dependent files:
```
python autogen.py generate_tf_guides
python autogen.py add_guide preprocessing_layers.py
```

Show the encoded text in the preprocessing guide

---

examples/vision/image_classification_efficientnet_fine_tuning.py
examples/vision/ipynb/image_classification_efficientnet_fine_tuning.ipynb
examples/vision/md/image_classification_efficientnet_fine_tuning.md

With reference to the [EfficientNet tutorial](https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/) the last line tries to load B1 weights into B0 which results in incompatibility problems. Additionally, I think it would be useful to just provide a link to the `efficientnet_weight_update_util.py` since[ it does not come with the standard installation](https://github.com/tensorflow/tensorflow/pull/40621#issuecomment-697340955). 
This PR address the above pointers.

Change EfficientNetB0 to EfficientNetB1 in the final line

---

examples/nlp/md/masked_language_modeling.md

A recent change https://github.com/keras-team/keras-io/commit/7c7d09ba9651dd8a05ccb70b2a0520d0a34c68cc updated some filenames, but the links to "view in colab" and "github source" were not updated.

Update masked_language_modeling colab and github links

---

templates/api/layers/regularizers.md

Correct a very small typo in the description of the subclass.

Correct typo in the description of the subclass.

---

guides/transfer_learning.py

Plot of (Dog)[ Data Augmentation example](https://keras.io/guides/transfer_learning/#standardizing-the-data) shows wrong labels (label 0 and 1) although label 1 (for dog) should be present only.

Fix: Plot of Data Augmentation example shows wrong labels

---

examples/generative/cyclegan.py
examples/generative/ipynb/cyclegan.ipynb
examples/generative/md/cyclegan.md

At the "Build the generators" the last layer is said to have `filter size of 1` but actually, it also has `filter size of 7` as the first layer, what may have caused the type is that it has `stride size of 1`.
Also the code implementation is used `filter size of 7`.

Correcting filter size typo

---

guides/ipynb/transfer_learning.ipynb
guides/md/transfer_learning.md
guides/transfer_learning.py

Fixed an error in a heading which made some part of it get displayed on a new line (without the ## format).

Fixed section heading in transfer_learning.py

---

guides/understanding_masking_and_padding.py

Isn't softmax divides by a (Sum over inputs_exp) and not by a (Sum over raw inputs)

Probable error in example "TemporalSoftmax"

---

templates/api/models/index.md

This PR updates the guide slug used in the `api/models` page in order to redirect to an existing page.
Indeed, it looks like the `model_subclassing` guide does not exist anymore and causes a 404.

Fix model subclassing guide link

---

examples/vision/ipynb/supervised-contrastive-learning.ipynb
examples/vision/md/supervised-contrastive-learning.md
examples/vision/supervised-contrastive-learning.py

Minor correction : in the SupervisedContrastiveLoss class, the logits should use the temperature class attribute instead of the global variable.

Minor correction to SupervisedContrastiveLoss

---

guides/md/transfer_learning.md

Tanser corrected to Transfer
datases corrected to datasets
These words are spelt correctly in the .ipynb and .py files

Minor changes to correct spellings

---

examples/audio/ipynb/transformer_asr.ipynb
examples/audio/md/transformer_asr.md
examples/audio/transformer_asr.py

Some decisions I made to keep this example short and easy to train:
- Model - Transformer (both encoder and decoder):
I picked a sequence to sequence approach instead of a CTC pipeline because we already have a good example showing the CTC setup. (OCR Captcha Recognition) and a CTC based example will be very similar to it.
- Data - Free spoken digit dataset:
A standard (and more realistic) dataset like LibriSpeech requires few hours for training (even with a V100) to reach a WER < 10%. Free spoken digit contains small segments of audio (<= 1 second) and a single word as the transcript (treated as a sequence of characters). This data is very easy to train on but demonstrates a complete sequence to sequence pipeline.
- To make it slightly more difficult I prepared another dataset from this, …

Speech recognition example - sequence to sequence using transformer

---

examples/vision/ipynb/oxford_pets_image_segmentation.ipynb
examples/vision/md/oxford_pets_image_segmentation.md
examples/vision/oxford_pets_image_segmentation.py

Very small PR to fix a typo from `Perpare` to `Prepare`

fix typo for oxford_pets_image_segmentation

---

templates/api/layers/initializers.md

In the current documentation on [Creating custom initializers](https://keras.io/api/layers/initializers/#creating-custom-initializers) for [layers](https://keras.io/api/layers/initializers/), the example code showing how to implement a random initializer is wrong indented.
This PR simply indents the class methods.

Indent methods in the code example for creating custom initializers

---

examples/graph/gnn_citations.py
examples/graph/ipynb/gnn_citations.ipynb
examples/graph/md/gnn_citations.md

Fixed typo in a comment in line 270. "model" instead of "mode".

Typo fix in gnn_citations.py

---

examples/vision/gradient_centralization.py
examples/vision/ipynb/gradient_centralization.ipynb
examples/vision/md/gradient_centralization.md

I noticed a really small typo in the the [Gradient Centralization for Better Training Performance](https://keras.io/examples/vision/gradient_centralization/) example and this PR fixes that.
Earlier it was (notice spacing):
> We will rescale the data to [0, 1]  andperform simple augmentations to our data.
Which this PR changes to:
> We will rescale the data to [0, 1] and perform simple augmentations to our data.

Fix a small typo in GC example

---

examples/vision/gradient_centralization.py
examples/vision/ipynb/gradient_centralization.ipynb
examples/vision/md/gradient_centralization.md

This PR fixes a minor typo in the gradient centralisation example.

Fix typo in gradient centralisation example.

---

templates/getting_started/faq.md

```
.../tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated 
and will be removed after 2021-01-01. Please use instead:
* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification
(e.g. if it uses a `softmax` last-layer activation).
* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification 
(e.g. if it uses a `sigmoid` last-layer activation).
```

Remove Model.predict_classes (deprecated) from FAQ

---

examples/timeseries/ipynb/timeseries_classification_from_scratch.ipynb
examples/timeseries/md/timeseries_classification_from_scratch.md
examples/timeseries/timeseries_classification_from_scratch.py

The FordA sequences length value is 500 instead of 176. This situation can be seen in the jupyter notebook and the .py file.
According to the paper and the code, the sequences length value is 500 instead of 176. I know that this is a minor detail, but it might be important to have that value correct for learning purposes.
Page 92 [Source](https://www.cs.ucr.edu/~eamonn/time_series_data_2018/BriefingDocument2018.pdf)
[Source](http://www.j-wichard.de/publications/FordPaper.pdf)

Fixing the comment line where the sequence length about the dataset was incorrect. 

---

guides/md/transfer_learning.md

This fixes a typo `worfklow` -> `workflow`.

fix: typo in transfer_learning.md

---

guides/ipynb/training_with_built_in_methods.ipynb
guides/md/training_with_built_in_methods.md
guides/training_with_built_in_methods.py

A proposed solution to fix a 404 on tensorflow.org. Because of case-sensitivity in URLs, the link on the same guide -  https://www.tensorflow.org/guide/keras/train_and_evaluate - points to https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/tensorboard/ which is a "404" (requires `...TensorBoard/`)

Use absolute link to TensorBoard callback in Training & evaluation with the built-in methods guide

---

templates/getting_started/faq.md

didn't insert a space into "whenrunning" since #560 already does this.
This is what the page currently looks like:

Fix FAQ (```endshell breaks things)

---

examples/vision/ipynb/perceiver_image_classification.ipynb
examples/vision/md/perceiver_image_classification.md
examples/vision/perceiver_image_classification.py

This will not change the behavior of the script but I believe the class was intended to use `self.num_iterations` in this place since the class sets `self.num_iterations` in `__init__()` but doesn't use it anywhere.

Use self.num_iterations instead of global variable

---

templates/api/preprocessing/index.md

- Fixing typo in importing `image_dataset_from_directory` function
- This function doesn't exist in the `.image` module, but in the `.preprocessing`
- And the same function used in this [article](https://keras.io/api/preprocessing/image/#image_dataset_from_directory-function) properly

image_dataset_from_directory function exists in .preprocessing not in .image

---

scripts/autogen.py

We will still have a number of links pointing to tensorflow.org,
but this links keras.io guides from keras.io symbol documentation
where possible.

Update docstring links to keras.io for keras guides

---

examples/vision/conv_lstm.py
examples/vision/ipynb/conv_lstm.ipynb
examples/vision/md/conv_lstm.md

The error happens in the data visualization step
```python
ax.imshow(train_dataset[data_choice][idx], cmap='gray')
TypeError: Invalid shape (64, 64, 1) for image data
```
The fix is just to squeeze the image with `np.squeeze` function.
The fix has been applied to `examples/vision/ipynb/conv_lstm.ipynb`, `examples/vision/conv_lstm.py` and `examples/vision/md/conv_lstm.md`

Fix image plot on lstm_conv example

---

examples/vision/ipynb/swin_transformers.ipynb
examples/vision/md/swin_transformers.md
examples/vision/swin_transformers.py

This is a really quick and small PR for the example I recently contributed, [Image classification with Swin Transformers](https://keras.io/examples/vision/swin_transformers). While my further experiments, I today noticed a really minor problem while saving the model using `model.save()`. We don't do this in the example which is why I might have missed it, but this change would be helpful if people want to take this example further and probably save the models they trained in this example.
Instead of using:
```py
rank = len(input_shape)
```
which creates problems on calling `model.save()` we now use the dynamic shape:
```py
rank = input_shape.shape.as_list()[0]
```

Make the Swin Transformer example model savable

---

examples/vision/ipynb/nnclr.ipynb
examples/vision/md/nnclr.md
examples/vision/nnclr.py

In this example we will be implementing NNCLR as proposed in the paper [With a LittleHelp from My Friends: Nearest-Neighbor Contrastive Learning of Visual Representations](https://arxiv.org/abs/2104.14548), by Google Research and DeepMind which:
- learns  self-supervised representations that go beyond single instance positives which allows to learn better features that are invariant to different viewpoints, deformations, and even intra-class variations
- Clustering based methods offer a great approach to go beyond single instance positives, but assuming the entire cluster  to be positives could hurt performance due to early over-generalization. Instead NNCLR uses nearest neighbors in the learned representation space as positives
- increases the performance of existing contrastive learning …

Self-supervised contrastive learning with NNCLR

---

guides/ipynb/keras_tuner/getting_started.ipynb
guides/ipynb/keras_tuner/tailor_the_search_space.ipynb
guides/keras_tuner/getting_started.py
guides/keras_tuner/tailor_the_search_space.py
guides/md/keras_tuner/getting_started.md
guides/md/keras_tuner/tailor_the_search_space.md
scripts/guides_master.py

New KerasTuner tutorial for 1.1.0 release.
Separate out part of the old tutorial to a new guide: tailor the search space.
Related RFC: [link](https://github.com/keras-team/governance/blob/b8a6ddd7d714fd73569b35b0f79963d012cfabd6/rfcs/20210920-tune-end-to-end-ml-workflows-in-keras-tuner.md)
This PR should not be merged until the new KT 1.1.0 release.

update getting started for kt 1.1.0

---

redirects/api/preprocessing/image/index.html
redirects/api/preprocessing/index.html
redirects/api/preprocessing/text/index.html
redirects/api/preprocessing/timeseries/index.html
scripts/master.py
templates/api/data_loading/index.md

These utilities symbols were moved from keras.preprocessing to
keras.utils, and the ones that are still listed are for loading
not manipulating data.

Rename keras preprocessing page to dataset loading

---

examples/vision/ipynb/token_learner.ipynb
examples/vision/md/token_learner.md
examples/vision/token_learner.py

In this example we (with @sayakpaul) have implemented [TokenLearner: What Can 8 Learned Tokens Do for Images and Videos?](https://arxiv.org/abs/2106.11297) with a smaller ViT for CIFAR-10 image classification. 
In the paper the authors suggest an adaptive token learning algorithm that makes ViT computationally much more efficient (in terms of FLOPs) and also increases downstream accuracy (here classification accuracy). Experimenting with CIFAR-10 we reduce the number of pathces from 64 to 4 (number of adaptively learned tokens) and also report a boost in the accuracy.
We think this should be a great addition to the keras examples as it would be accessible to the community for further research.
Colab Link: https://colab.research.google.com/drive/1zjAnHQ3LLfS47dxTqaWm77YAa7WljTXo?usp=sharing …

Add: Token Learner for Vision Transformer

---

templates/api/applications/index.md

Full list of changes:
* Completes the _Top-1_ and _Top-5_ accuracy columns for EfficientNet models, based on [Table 2 from the paper](https://arxiv.org/pdf/1905.11946.pdf).
* Completes and updates the _Depth_ ​column to count only layers with parameters, as it is the most common convention. For example, VGG16 and VGG19 are named this way because they have 16 and 19 layers respectively, excluding parameter-free layers.
* Adds a short sentence to explain the _Depth_ column.
* Shortens the _Parameters_ column by showing millions, instead of exact count.
* Updates the _Top-1_ and _Top-5_ columns to show percentages, with 1 decimal point.
* Rounds the inference time columns to 1 decimal point instead of 2.
* Reorders the ResNet models so that v1 and v2 models are contiguous (makes the …

Update applications table for completeness and readability

---

templates/api/applications/index.md

- Format Top-1 Accuracy and Top-5 Accuracy as percentages in line with models above. [1]
- Format Parameters count in millions in line with models above. [1]
- Add newline in front of sentence explaining top-1 and top-5 accuracy, so the explanation is outside the table in line with sentences explaining other columns. [2]
- Add newline in front of list of components so its formatted correctly as a list. [2]
- RAM in upper-case. [2]

Update formatting of Applications page

---

examples/vision/ipynb/shiftvit.ipynb
examples/vision/md/shiftvit.md
examples/vision/shiftvit.py

The reference to the warmup cosine was missing. I apologise for not getting to this earlier. Did not mean to plagarise any code. As soon as @sayakpaul noticed it and let me know, I made the changes.
Hope this is taken as my mistake and not otherwise.

Fix: Provide reference

---

templates/api/applications/index.md

Deleted the duplicate models which are starting from `EfficientNetV2B0` and ending at `EfficientNetV2L` in the table.
Fixes [#16303](https://github.com/keras-team/keras/issues/16303)

Deleted the duplicate models in the table

---

requirements.txt
scripts/autogen.py

The CodeHilite to the markdown renderer now supports the usual syntax,
and newer version appear to no longer supports the
`::: syntax`.
I'm not sure exactly when this happened, but we can just depend on
the latest version of python-markdown.

Stop replacing lang syntax for fenced markdown

---

examples/generative/ipynb/vq_vae.ipynb
examples/generative/md/vq_vae.md
examples/generative/vq_vae.py

There was a problem with the function get_decoder, because when it wants to get the output shape of the encoder, it directly calls the get_encoder function without parameter, so it assumes that the current latent_dim is the default latent_dim: 16. So, to address this issue, it can just pass the current latent_dim parameter when calling get_encoder function.

Fix vq_vae.py

---

examples/generative/ipynb/vq_vae.ipynb
examples/generative/md/vq_vae.md
examples/generative/vq_vae.py

The usage of the `sample()` method used here from tensorflow-probability doesn't work for any version after 0.13.0 for this particular example. See also: https://stackoverflow.com/questions/69620035/typeerror-dimension-value-must-be-integer-or-none-in-keras-vq-vae-example/72561898#72561898

VQ-VAE example: pin tensorflow-probability to last known working version

---

guides/ipynb/preprocessing_layers.ipynb
guides/md/preprocessing_layers.md
guides/preprocessing_layers.py

As discussed with @fchollet @mattdangerw @MarkDaoust 
This PR introduces the following improvements:
- Clarify that the Keras `TextVectorization` layer should be used as part of a `tf.data` input pipeline (runs only on CPUs, won't utilize hardware acceleration if included inside a `Model`, affecting performance).
- Perform some minor linting.
---
- Guide: Working with preprocessing layers (https://keras.io/guides/preprocessing_layers/, https://www.tensorflow.org/guide/keras/preprocessing_layers)
- Section: Preprocessing data before the model or inside the model

Clarify why TextVectorization works on CPU

---

examples/generative/ipynb/vq_vae.ipynb
examples/generative/md/vq_vae.md
examples/generative/vq_vae.py
scripts/autogen.py

This is a follow-up of #911 
With help from Christopher Suter, this removes the necessity for pinning the tensorflow-probability package, see https://github.com/tensorflow/probability/issues/1576 for the help he provided.
I took the liberty to rename the `x` variable to `layers`, which I believe to be more apt.

Refactor VQ-VAE example to work with recent versions of tensorflow-probability

---

examples/audio/ipynb/melgan_spectrogram_inversion.ipynb
examples/audio/md/melgan_spectrogram_inversion.md
examples/audio/melgan_spectrogram_inversion.py
examples/generative/ipynb/wgan-graphs.ipynb
examples/generative/md/wgan-graphs.md
examples/generative/wgan-graphs.py
examples/graph/ipynb/mpnn-molecular-graphs.ipynb
examples/graph/md/mpnn-molecular-graphs.md
examples/graph/mpnn-molecular-graphs.py
templates/examples/audio/melgan_spectrogram_inversion.md

As per the ongoing hugs keras sprint, have updated the following examples:
Audio Data:
- melgan_spectrogram_inversion
Graph Data:
- mpnn-molecular-graphs
Generative Deep Learning
- wgan-graphs
Will be glad to address any issues/changes.

Add model and space link for melgan_spectrogram_inversion, mpnn-molecular-graphs, wgan-graphs

---

guides/ipynb/serialization_and_saving.ipynb
guides/md/serialization_and_saving.md
guides/serialization_and_saving.py

Updated direct link to access `Custom Objects` definition by changing #custom-objects to #custom_objects in the given link.

Updated direct link for Custom Objects

---

examples/generative/ipynb/real_nvp.ipynb
examples/generative/md/real_nvp.md
examples/generative/real_nvp.py

layers.Normalization() does not exist in Tensorflow 2.3.0, which is listed as a requirement.
And Tensorflow_probability 0.11.0 (listed) is stable against tf 2.3.0 shown here https://github.com/tensorflow/probability/releases?page=2

Update to match required Tensorflow versions

---

guides/ipynb/serialization_and_saving.ipynb
guides/md/serialization_and_saving.md
guides/serialization_and_saving.py

Fixed Grammar mistakes at lines 24, 26, 27 and 389

Fixed Grammar mistakes

---

guides/ipynb/keras_cv/coco_metrics.ipynb
guides/keras_cv/coco_metrics.py
guides/md/keras_cv/coco_metrics.md

Throwing 404 error for bounding box format hyperlink.
So Put the working link for the bounding box format. 
https://keras.io/api/keras_cv/bounding_box/formats/

Put working link for bounding box format

---

examples/generative/cyclegan.py
examples/generative/ipynb/cyclegan.ipynb

This is the solution for [# 691](https://github.com/keras-team/keras-io/issues/691)
This fixes an issue that caused an error at CycleGan's Model Checkpoint.

fix cyclegan save error

---

templates/keras_nlp/index.md

We would like to have a spot where we curate the list of all examples
using the keras-nlp package. For now, we will do this on the keras-nlp
home page on keras.io.

Directly link guides and examples on keras-nlp

---

examples/vision/ipynb/oxford_pets_image_segmentation.ipynb
examples/vision/md/oxford_pets_image_segmentation.md
examples/vision/oxford_pets_image_segmentation.py

Clean-up codes.
- Only `ImageOps` module in PIL is used in the whole code. `import PIL` does nothing.

Remove importing PIL

---

requirements.txt

I noticed the black version in continuous_integration.yml is different from the version mentioned in requirements file:
https://github.com/keras-team/keras-io/blob/master/.github/workflows/continuous_integration.yml
This is causing differences in formatting of python file done locally vs the formatting check happening as part of the workflow run and causing the check for black to fail 
Hence updating requirements file to match version mentioned in continuous_integration.yml

Updated black version in requirements.txt 

---

examples/nlp/ipynb/pretraining_BERT.ipynb
examples/nlp/md/pretraining_BERT.md
examples/nlp/pretraining_BERT.py

This code example shows how to pre-train BERT using Hugging Face transformers on NSP + MLM tasks. Additionally, it also shows best practices for Hugging Face Datasets.
@fchollet apologies for the duplicate PR on this, but due to shared machines between teammates, the original PR #966 messed up a bit with GitHub usernames pushing to the code and Google needing CLA. This has all the changes mentioned and is ready for merging!

New Code Example: Pre-training BERT on NSP+MLM using Hugging Face Transformers

---

templates/api/applications/index.md

Since ConvNeXt models have been merged (https://www.tensorflow.org/api_docs/python/tf/keras/applications/convnext) I thought it might be a good idea to include them under `keras.io/applications`.

chore: add convnext models.

---

requirements.txt

We don't need to explicitly pull in the pre-release anymore.

Tf text 2.10 is out, we can stop pinning

---

guides/preprocessing_layers.py

Corrected the spelling 
1. Changed `normalize` to `normalization`
2.  batch of `image` to batch of `images`

Fix typos in preprocessing_layers.py

---

examples/vision/image_captioning.py
examples/vision/ipynb/image_captioning.ipynb
examples/vision/md/image_captioning.md

In the `image_captioning.md`, make_dataset consists of variables that are not defined. (`split`, `read_train_image` and `read_valid_image`)
```py
def make_dataset(images, captions):
if split == "train":
img_dataset = tf.data.Dataset.from_tensor_slices(images).map(
read_train_image, num_parallel_calls=AUTOTUNE
)
else:
img_dataset = tf.data.Dataset.from_tensor_slices(images).map(
read_valid_image, num_parallel_calls=AUTOTUNE
)
cap_dataset = tf.data.Dataset.from_tensor_slices(captions).map(
vectorization, num_parallel_calls=AUTOTUNE
)
dataset = tf.data.Dataset.zip((img_dataset, cap_dataset))
dataset = dataset.batch(BATCH_SIZE).shuffle(256).prefetch(AUTOTUNE)
return dataset
```
```py
def make_dataset(images, captions):
dataset = tf.data.Dataset.from_tensor_slices((images, captions))
dataset = …
```

bug: Image_Captioning.md Fixed

---

guides/keras_cv/generate_with_stable_diffusion.py

This shows how to tune XLA performance, etc.
TODOS:
Check out a rendered preview here: 
https://nbviewer.org/github/LukeWood/Devoxx/blob/master/Basic%20Generation.ipynb

Add `keras_cv.models.StableDiffusion()` guide

---

guides/ipynb/keras_tuner/getting_started.ipynb
guides/keras_tuner/getting_started.py
guides/md/keras_tuner/getting_started.md

Without the extra newline at its start, keras.io renders the first item as part of the preceding paragraph, see
[screenshot](https://user-images.githubusercontent.com/37290325/195843643-06d93dd7-f4bf-43e5-bda6-5ac14157069f.png).

Fix markdown syntax for a list in the KerasTuner guide.

---

.github/workflows/continuous_integration.yml

This fixes the black CI. The docker one is accidentally fixed by #1148.
black 22.1.0 is not compatible with the current version of `click` and fails on run. 
black 22.3.0 is, and seems to be working with the rest of the project (see the requirements.txt).
Ci is failing in:
https://github.com/keras-team/keras-io/pull/1149
https://github.com/keras-team/keras-io/pull/1148
with:
```
Successfully installed black-22.1.0 click-8.1.3 mypy-extensions-0.4.3 pathspec-0.10.2 platformdirs-2.6.0 tomli-2.0.1 typing-extensions-4.4.0
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.9.15/x64/bin/black", line 8, in <module>
sys.exit(patched_main())
File "src/black/__init__.py", line 1423, in patched_main
File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import …
```

Fix CI: Update black version to match requirements.txt

---

guides/ipynb/keras_cv/generate_images_with_stable_diffusion.ipynb
guides/keras_cv/generate_images_with_stable_diffusion.py
guides/md/keras_cv/generate_images_with_stable_diffusion.md

Fix the broken code link to keras-cv in "High-performance image generation using Stable Diffusion in KerasCV" tutorial file. https://www.tensorflow.org/tutorials/generative/generate_images_with_stable_diffusion
Recreate PR in order to change all relative files (md, py, ipynb) . Previous PR: https://github.com/keras-team/keras-io/pull/1161

Fix the broken link in Stable diffusion tutorial

---

templates/api/keras_nlp/index.md

Need absolute reference to link to guide from the API page.
TESTED: built site locally and checked link.

Fix broken link for KerasNLP Getting Started guide

---

guides/ipynb/keras_nlp/getting_started.ipynb
guides/ipynb/keras_nlp/transformer_pretraining.ipynb
guides/keras_nlp/getting_started.py
guides/keras_nlp/transformer_pretraining.py
guides/md/keras_nlp/getting_started.md
guides/md/keras_nlp/transformer_pretraining.md
templates/keras_nlp/index.md

We will use the same install line everywhere which will update tensorflow to the latest version (useful for colab with old tf).
Also switch the optimizer from AdamW -> Adam in our quickstart, as AdamW does not converge on tf 2.9, and the quickstart may be copied and pasted into a lot of environments we don't control.

Some minor fixes for keras-nlp docs

---

scripts/cv_api_master.py
templates/keras_cv/bounding_box/index.md

Lets still hold off on the v0.4.0 publicity push until:
- keras.io/guides/retinanet is fixed
- keras.io/keras_cv is updated
I will update keras.io/keras_cv in a separate PR

Update API symbols + genapi specs

---

Dockerfile
requirements.txt

Solves: #1201 
I was trying to build the docker container, but it showed errors due to mismatched dependencies.
```py
You do not have pycocotools installed, so KerasCV pycoco metrics are not available. Please run `pip install pycocotools`.
```
Also had to downgrade `keras-cv` as 
```py
RuntimeError: For project keras_cv, URL https://github.com/keras-team/keras-cv/tree/v0.3.4/ has version number 0.3.4 which does not match the current imported package version 0.4.1
```
Also had to get `keras-nlp` from the source as pip didn't have the latest version 0.4.0 available and had to upgrade python as keras-nlp doesn't support `python:3.7`.

Updated Dependencies and DockerFile

---

guides/ipynb/understanding_masking_and_padding.ipynb
guides/md/understanding_masking_and_padding.md
guides/understanding_masking_and_padding.py

Updated masking_and_padding with new apis
Old api - tf.keras.preprocessing.sequence.pad_sequences
new api - tf.keras.utils.pad_sequences
Attached [old](https://colab.sandbox.google.com/github/tensorflow/docs/blob/snapshot-keras/site/en/guide/keras/masking_and_padding.ipynb#scrollTo=bb64fb185a05) and [new](https://colab.sandbox.google.com/gist/mohantym/e0939e8637ea2f6d05a180144e8281b9/masking_and_padding.ipynb#scrollTo=906e07f6e562) gist for reference.

Updated masking_and_padding with new apis

---

requirements.txt

If not pin the versions of the Keras packages (CV, NLP, Tuner), the CI will always pick the latest version to install.
It breaks whenever a new version is released due to inconsistency with the version specified in `autogen.py`.

Pin the Keras packages versions

---

theme/css/landing.css

Some images of the landing page are not responsive on some devices. So I played with the CSS of the landing page and found out that `min-height: 20rem` works better than `min-height: 25rem`. That's why I changed it to 20rem.

Added responsiveness to landing page images.

---

scripts/autogen.py

Keras-NLP version in `requirements.txt` was updated to `0.4.1` (#1244).  This also needs to be updated in the `autogen.py` URL for the project.

Update Keras-NLP version to match requirements

---

examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb
examples/nlp/md/neural_machine_translation_with_transformer.md
examples/nlp/neural_machine_translation_with_transformer.py

Fixes Issue #1252 by adjusting the `padding_mask` broadcast in `TransformerEncoder` to be same as `TransformerDecoder`.  Tested in TensorFlow 2.9 and also in 2.11 on Colab.

Fix padding mask broadcasting for encoder transformer

---

examples/generative/ipynb/random_walks_with_stable_diffusion.ipynb
guides/ipynb/keras_cv/generate_images_with_stable_diffusion.ipynb

Remove Cuda 11.2 install steps from Notebooks since its no longer required for Colab.

Remove Cuda Install Steps

---

guides/ipynb/keras_cv/cut_mix_mix_up_and_rand_augment.ipynb
guides/keras_cv/cut_mix_mix_up_and_rand_augment.py
guides/md/keras_cv/cut_mix_mix_up_and_rand_augment.md

1) change all `from tensorflow.keras import ~` to `from keras import ~` since the guide imports `from tensorflow import keras` previously. Before the change, those import lines prompt errors while running the file in both local and Google Colab. 
2) fix a minor spelling typo.
3) Not sure why those lines of code are written (I guess redundant). The code works perfectly okay without those lines, so I delete it. However, I will revert the change if you suggest to keep those lines.

fix typos in 'image augmentation with KerasCV' guide

---

guides/ipynb/keras_cv/retina_net_overview.ipynb
guides/keras_cv/retina_net_overview.py
guides/md/keras_cv/retina_net_overview.md

- found some misspellings and punctuation errors in KerasCV guide, so I fixed them.
Comment down below if there are any other parts to change. I will update .ipynb and .md files accordingly if all things are set!

fix typos in KerasCV guide using RetinaNet

---

examples/nlp/ipynb/t5_hf_summarization.ipynb
examples/nlp/md/t5_hf_summarization.md
examples/nlp/t5_hf_summarization.py

Without installing the 'rouge-score' package using 'pip install rouge-score', attempting to run 'rouge_l = keras_nlp.metrics.RougeL()' will result in an error message: 'ImportError: RougeL requires the rouge_score package. Please install it with pip install rouge-score.'

Add missing dependency and make pip commands runnable on Google Colab

---

examples/nlp/ipynb/t5_hf_summarization.ipynb
examples/nlp/md/t5_hf_summarization.md
examples/nlp/t5_hf_summarization.py

made 3 commits:
**commit-1**
Changed 't5-base' to 't5-small'
In 'Define certain variables' section the MODEL_CHECKPOINT is defined as "t5-small" and also based on this console output 'Downloading:   0%|          | 0.00/231M [00:00<?, ?B/s]',  it seems "t5-small" is the right.
**commit-2**
Removed 'validation' text
'''
raw_datasets = raw_datasets.train_test_split(
train_size=TRAIN_TEST_SPLIT, test_size=TRAIN_TEST_SPLIT
)
'''
Here we divided out raw_datasets in to training and test set with no validation set. So I think removing the word 'validation' here is right.
**commit-3**
fixed spelling error
Changed 'me summarized' to 'be summarized'

Updated the t5_hf_summarization.py

---

examples/keras_recipes/ipynb/reproducibility_recipes.ipynb
examples/keras_recipes/md/reproducibility_recipes.md
examples/keras_recipes/reproducibility_recipes.py

This quick Keras recipe demonstrates how Keras initializers behave, and shows what's needed to achieve identical results in subsequential runs in model training process.
#1332

[Add Example] Create reproducibility_recipes.py

---

examples/nlp/ipynb/text_classification_from_scratch.ipynb
examples/nlp/md/text_classification_from_scratch.md
examples/nlp/text_classification_from_scratch.py

Thinking some people might can get confused about why we're not deleting other files, so I've added text specifying that we're only deleting the subfolders that contain txt files.

Added some text to enhance clarity

---

README.md
scripts/tutobooks.py

Every example header needs to have 6 rows. This condition is implemented in the code, but the 6th line should contain info about `Accelerator`, this thing was missing.
So I added additional checks with existing header conditions to verify two things
1. 6th row contains info about `Accelerator`
2. Its value is one of the possible values `GPU`, `TPU`, or `None`
Info about `Accelerator` and its possible values is also added in `README`.

Adding header Accelerator field details

---

guides/serialization_and_saving.py

This PR adds the new saving guide, titled "Save, serialize, and export", for the TF 2.13 release. It will replace the previous guide titled "Serialization and saving".
This new guide demonstrates the new Keras saving and export APIs, along with some parts carried over from the previous guide.
This PR should be merged at the time of the TF 2.13 release to avoid any confusion.

Add new saving guide and delete old guide

---

guides/md/training_with_built_in_methods.md

Fixed broken links for `Customizing what happens in fit()` and `Writing a training loop from scratch`.

Fixed Broken links

---

guides/md/functional_api.md

Fixed the broken link for **customizing_what_happens_in_fit**  in `functional_api.md`

Fixed the broken link in functional_api.md

---

examples/audio/ipynb/transformer_asr.ipynb
examples/audio/md/transformer_asr.md
examples/audio/transformer_asr.py

In the example tutorial of `Automatic Speech Recognition with Transformer`, positional embedding `self.pos_emb` in the class `SpeechFeatureEmbedding` has initialised but not used anywhere.
Hence I am proposing to remove this line of code to avoid unnecessary confusion.
Fixes #1394 
Thanks

remove unwanted code from transformer_asr.py

---

examples/vision/handwriting_recognition.py
examples/vision/ipynb/handwriting_recognition.ipynb
examples/vision/md/handwriting_recognition.md

Updated dataset link
Closes: https://github.com/keras-team/keras-io/issues/1399

Update dataset link

---

examples/nlp/ipynb/sentence_embeddings_with_sbert.ipynb
examples/nlp/md/sentence_embeddings_with_sbert.md
examples/nlp/sentence_embeddings_with_sbert.py
examples/nlp/sentence_embeddings_with_siamese_bert.py

this is an example of how to use RoBERTa from keras-nlp in another model and fine-tune it using siamese networks for semantic similarity tasks.
I fine tuned the model with two methods (regression objective and triplet objective).
the paper that this example is based on is [sbert](https://arxiv.org/abs/1908.10084)
here is a colab [gist](https://colab.research.google.com/gist/abuelnasr0/ef0aeccc5f420f8babf0f9a78e1cd874/sbert_jun19.ipynb) with the code.

sentence embeddings with Sbert.

---

examples/structured_data/deep_neural_decision_forests.py
examples/structured_data/ipynb/deep_neural_decision_forests.ipynb
examples/structured_data/md/deep_neural_decision_forests.md

In this file, `hidden_units = [64, 64]` initiated but not used anywhere. It's better to remove this line to avoid unwanted confusions for users.
Also Fixes #536 .

remove unused variable in deep_neural_decision_forests.py

---

examples/nlp/ipynb/semantic_similarity_with_keras_nlp.ipynb
examples/nlp/md/semantic_similarity_with_keras_nlp.md
examples/nlp/semantic_similarity_with_keras_nlp.py

Issue : https://github.com/keras-team/keras-nlp/issues/726
Kaggle Tutorial [Link](https://www.kaggle.com/code/shivanshuman/kerasnlp-semantic-similarity-with-bert/notebook)
This PR continues the previous PR #1253 
This PR ports Keras-io's existing [Semantic Similarity with BERT](https://keras.io/examples/nlp/semantic_similarity_with_bert/) to KerasNLP. Now the tutorial is pure Keras + tensorflow. It doesn't depend on Tensorflow at all.

Add `Semantic Similarity with KerasNLP` tutorial

---

examples/structured_data/feature_space_advanced.py
examples/structured_data/ipynb/feature_space_advanced.ipynb
examples/structured_data/md/feature_space_advanced.md

This PR adds a code example titled "FeatureSpace advanced use cases".
This work is part of the "Keras Community Sprint 2023" work that I am collaborating with @fchollet , the topic was his suggestion and I built the code, let me know if it is looking good, or if I need to change something here.
If you prefer there is also a [Colab version of this code](https://colab.research.google.com/drive/1RQL3asuAGPNFZ7JwUKHtu9eq3dG7h6lq?usp=sharing)
A few notes:
- I used the same dataset as the previous guide, I don't think that this is the best one to showcase the complex use cases of FeatureSpace, but I did not like the other options a lot either.
- For Francois, you suggested that the guide should also cover handling missing values, did you mean using `num_oov_indices=1` to cover unseen values or …

Adding "FeatureSpace advanced use cases" example

---

examples/vision/image_classification_from_scratch.py

This PR fixes the task as part of the project raised during Keras Community Sprint. Some important notes to add:
- It adds a KerasCV dependency to the example
- Makes a few changes to the text of the tutorial
- Uses `keras_cv.visualizations.plot_image_gallery` to visualize images, instead of the original manual implementation
- Uses `keras_cv.layers.RandomFlip` and `keras_cv.layers.RandAugment` in sequential format, for data augmentation.
Please let me know if any additions or changes should be made, to align it with KerasCV more.
@martin-gorner @ianstenbit @fchollet

[Keras Sprint] Add KerasCV visualizations and augmentations to 'Image Classification From Scratch' example

---

guides/serialization_and_saving.py

In the example of a `CustomLayer` class its `__init__` method passed argument `sublayer` whereas while assigning to self it is using the variable `layer` instead of `sublayer`. Hence corrected the same.
Also please check the documentation below.
> If the arguments passed to the constructor (`__init__()` method) of the custom object aren't Python objects (anything other than base types like ints, strings, etc.), then you **must** also explicitly deserialize these arguments in the `from_config()` class method.
Actually we need to also add the statement like you must explicitly serialize the `non_python arguments` in `get_config()` method also so that it can be deserialized in `from_config()` method. As it is explicitly mentioned for `from_config()` it should be explicitly mentioned for …

Update custom_object documentation and __init__() arg serialization_and_saving.py

---

examples/vision/image_classification_from_scratch.py
examples/vision/ipynb/image_classification_from_scratch.ipynb
examples/vision/md/image_classification_from_scratch.md

Adding a line to display the test image used for prediction. The reason is to provide a better understanding of how the predictions are linked with image being tested.
Original PRs - #1091 , #1075

Display test image

---

templates/keras_cv/index.md

Resolves keras-team/keras-cv#2022

Update KerasCV quickstart to match github

---

requirements.txt

Updated keras-core version which is blocking docker build process of CI activity.

Update keras-core version

---

examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb
examples/nlp/md/neural_machine_translation_with_transformer.md
examples/nlp/neural_machine_translation_with_transformer.py

At Line No.157 in neural_machine_translation_with_transformer.py, it was mentioned: 
> `encoder_inputs` is the vectorized source sentence and `encoder_inputs` is the target sentence "so far",
Actually `the target sentence "so far" `, should be `decoder_inputs`  instead of `encoder_inputs`
Corrected the same.
Shall fix #1002

Correct typo mistake in neural_machine_translation_with_transformer.py

---

examples/vision/ipynb/mobilevit.ipynb
examples/vision/md/mobilevit.md
examples/vision/mobilevit.py

The mobile vit tutorial will break due to import statement which was changed from Tf2.13V onwards.This works fine upto Tf2.12 versions.
Hence I changed the import statement to make it work for Tf2.13 and higher versions. Also added a note regarding this to make users aware of how to change the import for TF<=2.12 versions.
Also attached gist for same. Refer [gist-2.13vS](https://colab.sandbox.google.com/gist/SuryanarayanaY/bae80ee6e340f279637c2fe64fe6e49e/mobilevit-kerasio-1530_fixed-tf2-13v.ipynb) that is executed fine with the above change and [gist-2.13vF](https://colab.sandbox.google.com/gist/SuryanarayanaY/359a68752c4bd5d9b7c919ff67560ad1/mobilevit-kerasio-1530.ipynb) that failed without the proposed change.
Fixes #1530

Update import statement in mobilevit tutorial for TF>=2.13v

---

examples/generative/fine_tune_via_textual_inversion.py
examples/generative/ipynb/fine_tune_via_textual_inversion.ipynb
examples/generative/md/fine_tune_via_textual_inversion.md

Fixes the rendering issue in .md file which ignores <> symbol, replaced with &lt;my-funny-cat-token&gt; to render in html as intended.
Fixes: #1154 
Working Gist: https://colab.sandbox.google.com/gist/sachinprasadhs/763ef4c12af2189fc3baed473a719300/fine_tune_via_textual_inversion.ipynb

Fix rendering issue

---

scripts/docstrings.py

Maybe not the most beautiful fix, but we now support up to 9999 code blocks per docstring.

Fix rendering issue for >10 code blocks

---

examples/nlp/ipynb/ner_transformers.ipynb
examples/nlp/md/ner_transformers.md
examples/nlp/ner_transformers.py

Tensorflow only with preprocessing and some modeling ops in tf, but it should not be too hard to port this to multi backend with tf-only preprocessing in the future.
I believe there was a bad bug in this examples, where it computed a loss of softmax outputs with from_logits=True. Fixed.

Keras 3 ner_transformers

---

guides/ipynb/keras_nlp/transformer_pretraining.ipynb
guides/keras_nlp/transformer_pretraining.py
guides/md/keras_nlp/transformer_pretraining.md

embedding_weigths is no longer a argument of MaskedLMHead
instead it takes token_embeddings directly
Reference: 
https://keras.io/api/keras_nlp/modeling_layers/masked_lm_head/#:~:text=token_embedding%3A%20Optional.%20A%20keras_nlp.layers.ReversibleEmbedding%20instance.%20If%20passed%2C%20the%20layer%20will%20be%20used%20to%20project%20from%20the%20hidden_dim%20of%20the%20model%20to%20the%20output%20vocabulary_size.

token_embedding fix depriciation

---

requirements.txt
scripts/autogen.py

This doesn't actually change any symbols (it's only for adding Keras 3 support), but still good to track the latest release here.

Bump KerasNLP version to 0.6.3

---

guides/ipynb/working_with_rnns.ipynb
guides/md/working_with_rnns.md
guides/working_with_rnns.py

A quick fix for a "typo" that I found in: [Define a custom cell that supports nested input/output](https://www.tensorflow.org/guide/keras/working_with_rnns#define_a_custom_cell_that_supports_nested_inputoutput).
I think there is a `self.` missing for `unit_2` in `return {"unit_1": self.unit_1, "unit_2": unit_2, "unit_3": self.unit_3}`

Added missing .self to unit_2 in "Custom cell that supports nested input/output"

---

examples/generative/finetune_stable_diffusion.py
examples/generative/ipynb/finetune_stable_diffusion.ipynb
examples/generative/md/finetune_stable_diffusion.md

Fix import error by upgrading the version of `keras-cv` and add installation internal dependency keras-core.
As per the updated keras-cv, there is no need to provide image input shape in `StableDiffusion` for `ImageEncoder` Ref Commit # https://github.com/keras-team/keras-cv/commit/67efa6152ee0a513d79d25ef68cf2128b26a5e04
Closes: https://github.com/keras-team/keras-io/issues/1555

Fix import error

---

guides/intro_to_keras_for_engineers.py

Broken Link:
https://keras.io/guides/custom_train_step_in_pytorch/
Corrected Link:
https://keras.io/guides/custom_train_step_in_torch/
---
IMO, the target URL should have been renamed to "_in_pytorch" to be consistent with the official name of the framework.

intro_to_keras_for_engineers.py: Fix broken link

---

examples/vision/ipynb/simsiam.ipynb
examples/vision/md/simsiam.md
examples/vision/simsiam.py

This PR migrates the `simsiam` example to Keras 3.0 as requested in [this GitHub issue](https://github.com/keras-team/keras-cv/issues/2211) and includes the following changes:
1. Hardcoded the backend to TF-only to align with the fact that it's a TF-only example.
2. Replaced the dependency on TensorFlow-based data augmentation with a Keras-based pipeline, involving:
- Substitution of TensorFlow image preprocessing functions with equivalent keras and keras-cv layers.
- Initialization of layers outside the function to resolve the "ValueError: tf.function only supports singleton tf.Variables created on the first call. Make sure the tf.Variable is only created once or created outside tf.function" issue after implementing the earlier mentioned changes.
- Modification of arguments for the …

Migrating SimSiam Example to Keras-3

---

examples/keras_recipes/ipynb/tfrecord.ipynb
examples/nlp/ipynb/text_extraction_with_bert.ipynb
examples/nlp/text_extraction_with_bert.py
examples/vision/ipynb/xray_classification_with_tpus.ipynb

There are 4 notebooks that specify `Accelerator: TPU`, however their IPython metadata still specified `GPU` as the accelerator, so the Colab would open with the incorrect accelerator.
Example at HEAD:
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/xray_classification_with_tpus.ipynb
Validation of fix:
https://colab.research.google.com/github/jeffcarp/keras-io/blob/fix-colab-tpu-metadata/examples/vision/ipynb/xray_classification_with_tpus.ipynb
Fixed by re-exporting the .py files to .ipynb, using command:
```
python3 tutobooks.py py2nb ../examples/keras_recipes/tfrecord.py ../examples/keras_recipes/ipynb/tfrecord.ipynb
```

Fix notebooks using Colab TPU

---

scripts/autogen.py

Fixes https://github.com/keras-team/keras-io/issues/1696
This replacement breaks:
- install commands like `pip install --upgrade keras` which can no longer be copy-pasted
- anchors in pages like https://keras.io/getting_started/#tensorflow--keras-2-backwards-compatibility

Do not replace double dashes with m-dash.

---

scripts/autogen_utils.py

This way code blocks, anchors, etc. are not affected.

Transform double dashes to n-dash using the Smarty plugin.

---

redirects/getting-started/index.html
templates/contributing.md

There are still links to `https://keras.io/getting-started/` in the wild. Sub-pages of the getting-started page already have redirects.
Also fixed a getting-started link in the contributing guide.

Add a redirect for the top-level getting-started page.

---

examples/vision/deeplabv3_plus.py
examples/vision/ipynb/deeplabv3_plus.ipynb
examples/vision/md/deeplabv3_plus.md

I came across this example and noticed an unused function argument that is not used anywhere. I intend to enhance the readability of the example by removing the argument.

tiny: Remove unused function arg in DeepLabV3+ example

---

guides/ipynb/keras_cv/classification_with_keras_cv.ipynb
guides/keras_cv/classification_with_keras_cv.py
guides/md/keras_cv/classification_with_keras_cv.md

The reason for these modifications is actually not an error but rather a section of code that was repeated twice during the guide's writing. Here is a picture of it
This code attempts to resize the evaluation dataset for inference; however, it is duplicated twice throughout the py, md, and ipynb files. Additionally, resizing was already completed for the train dataset in the form of an augmentation layer. Consequently, not for the train dataset either.
I did not raise any issues about it because it did not result in any errors. I have just made a pull request and eliminated the recurring instances.
cc: @fchollet

Repeat code for the kerasCV image classification guide

---

scripts/cv_api_master.py

Currently keras_cv supports 3 more bounding box formats than what is mentioned in the documentation. This PR adds those remaining paths in `cv_api_master.py`.

Added the remaining bounding box formats from keras_cv

---

guides/writing_a_custom_training_loop_in_jax.py

The `optimizer.stateless_apply` takes the optimizer's variables as the first positional argument but the `grads` variable was being passed which results in error.

Fix positional arguments to `optimizer.stateless_apply`

---

examples/vision/ipynb/nnclr.ipynb
examples/vision/md/nnclr.md
examples/vision/nnclr.py

This PR migrates the `nnclr` example to Keras 3.0 as requested in https://github.com/keras-team/keras-cv/issues/2211.
1. The tutorial has tensorflow dependency for data preprocessing due to `tf.data` and `tf.image.crop_and_resize()` function. 
2. Tested the code with `torch` and `jax` backends and works fine.

Migrating Nnclr to Keras-3[TF BackEnd]

---

templates/getting_started/index.md

Slight update to installation instructions. Upcoming docs will be pointing to this page so I updated it to make it more suitable for regular users (Colab, Kaggle) as well as advanced users like contributors running Keras tests.

updated installation instructions

---

examples/vision/ipynb/mobilevit.ipynb
examples/vision/md/mobilevit.md
examples/vision/mobilevit.py
scripts/examples_master.py

Updates the MobileViT example to use the latest Keras v3 syntax.

Updated MobileViT example to Keras v3

---

examples/graph/gnn_citations.py
examples/graph/ipynb/gnn_citations.ipynb
examples/graph/md/gnn_citations.md

There is an optional GRU code path in the gnn_citations.(py|md|ipynb). However it doesn't currently work.
The combination_type "gated" should be "gru"
If you set the combination_type to "gated" you get back a ValueError:
"Invalid combination type: gated"  from the aggregate method call
Fixing that issue exposes another issue in that "layers.GRU" units must be an integer and not a list as it currently is `hidden_units`
To resolve this I made a method to match the signature of the create_ffn and add multiple GRU layers
However it complicates the example a bit...
Also the use of hidden units like this doesn't work if  the hidden_layer sizes are different.
If you are happy with this change I will also update the ipynb and md files.

gnn_citations.(py|md|ipynb) GRU code path does not work

---

examples/rl/actor_critic_cartpole.py
examples/rl/ipynb/actor_critic_cartpole.ipynb
examples/rl/md/actor_critic_cartpole.md

This PR changes the [Actor Critic Method](https://keras.io/examples/rl/actor_critic_cartpole/) example to Keras 3.0 [TF Only Backend].
https://colab.research.google.com/drive/15pFWOBmb0bVPv7qmAFC2zjMzUiQeAbuT?usp=sharing
cc: @fchollet @divyashreepathihalli 
```
diff --git a/examples/rl/actor_critic_cartpole.py b/examples/rl/actor_critic_cartpole.py
index 14787341..e34000d3 100644
--- a/examples/rl/actor_critic_cartpole.py
+++ b/examples/rl/actor_critic_cartpole.py
@@ -39,11 +39,15 @@ remains upright. The agent, therefore, must learn to keep the pole from falling
"""
+import os
+
+os.environ["KERAS_BACKEND"] = "tensorflow"
import gym
import …
```

Migrating Actor Critic Method example to Keras 3 (TF-Only)

---

examples/audio/ipynb/uk_ireland_accent_recognition.ipynb
examples/audio/md/uk_ireland_accent_recognition.md
examples/audio/uk_ireland_accent_recognition.py
examples/generative/dreambooth.py
examples/generative/ipynb/dreambooth.ipynb
examples/generative/ipynb/molecule_generation.ipynb
examples/generative/ipynb/pixelcnn.ipynb
examples/generative/ipynb/wgan-graphs.ipynb
examples/generative/md/dreambooth.md
examples/generative/md/molecule_generation.md
examples/generative/md/pixelcnn.md
examples/generative/md/wgan-graphs.md
examples/generative/molecule_generation.py
examples/generative/pixelcnn.py
examples/generative/wgan-graphs.py

Fixed typos in examples/audio,examples/generative modules.

Fixed typos in examples/audio,examples/generative modules

---

examples/structured_data/ipynb/imbalanced_classification.ipynb

Fix typo in imbalanced classification notebook.
The notebook is not working. Error:
Remove the comma fixed it.

Fix imbalanced classification notebook.

---

examples/vision/ipynb/semisupervised_simclr.ipynb
examples/vision/md/semisupervised_simclr.md
examples/vision/semisupervised_simclr.py

Corresponding [Issue](https://github.com/keras-team/keras-cv/issues/2211)
This PR updates the [Semi-supervised image classification using contrastive pretraining with SimCLR](https://keras.io/examples/vision/semisupervised_simclr/#semisupervised-image-classification-using-contrastive-pretraining-with-simclr) Keras 3.0 example [TF Only Backend]. Many TF ops are replaced with corresponding Keras ops.
https://colab.research.google.com/drive/1rLAKohQaybEuUR-Nxgl3VDjZ8g5qmzid?usp=sharing
cc: @fchollet @divyashreepathihalli 
```
diff --git a/examples/vision/semisupervised_simclr.py b/examples/vision/semisupervised_simclr.py
index …
```

Updating Semi-supervised image classification using contrastive pretraining with SimCLR Keras 3 example (TF-Only)

---

templates/getting_started/index.md

Set TensorFlow version to 2.16.1 in Getting Started Page and also allow for minor version update.

Set TF Version to 2.16.1 (2.16.0 was yanked)

---

examples/generative/md/text_generation_fnet.md

For the [Text Generation using FNet example](https://keras.io/examples/generative/text_generation_fnet/) broken colab and github source links have been fixed.
cc: @fchollet

Link fixes for Text Generation using FNet example

---

examples/vision/captcha_ocr.py
examples/vision/ipynb/captcha_ocr.ipynb
examples/vision/md/captcha_ocr.md

This PR updates the [OCR model for reading Captchas](https://keras.io/examples/vision/captcha_ocr/) Keras 3.0 example [TF Only Backend]. Many TF ops are replaced with corresponding Keras ops.
https://colab.research.google.com/drive/1vCDb45wLmSI3iBI2_BfDDYDSztgxZ4Qp?usp=sharing
cc: @fchollet @divyashreepathihalli 
```
diff --git a/examples/vision/captcha_ocr.py b/examples/vision/captcha_ocr.py
index 3a2b8e96..06115b0f 100644
--- a/examples/vision/captcha_ocr.py
+++ b/examples/vision/captcha_ocr.py
@@ -35,6 +35,7 @@ from collections import Counter
import tensorflow as tf
import keras
+from keras import ops
from keras import layers
"""
@@ …
```

Updating OCR model for reading Captchas Keras 3 example (TF-Only)

---

templates/getting_started/benchmarks.md

We have used `torch.compile(model, mode="reduce-overhead")` in the benchmarks. Results are updated accordingly.
The numbers almost remain the same except BERT.
Changed BERT batch size because native PyTorch would run OOM with the old batch sizes using the given compile setting.

Update results as we changed torch compile to optimal setting

---

examples/nlp/ipynb/masked_language_modeling.ipynb
examples/nlp/masked_language_modeling.py
examples/nlp/md/masked_language_modeling.md

This PR changes the [End-to-end Masked Language Modeling with BERT](https://keras.io/examples/nlp/masked_language_modeling/) example to Keras 3.0 [TF Only Backend].
https://colab.research.google.com/drive/1O6uJdUeZzQMl7T6sKlMu5gZaUtM2U-nU?usp=sharing
cc: @fchollet 
```
diff --git a/examples/nlp/masked_language_modeling.py b/examples/nlp/masked_language_modeling.py
index 6378079e..6997a2b1 100644
--- a/examples/nlp/masked_language_modeling.py
+++ b/examples/nlp/masked_language_modeling.py
@@ -43,10 +43,14 @@ Note: This example should be run with `tf-nightly`.
Install `tf-nightly` via `pip install tf-nightly`.
"""
+import os
+ …
```

Migrating End-to-end Masked Language Modeling with BERT example to Keras 3

---

templates/getting_started/benchmarks.md

The change was to compile the train or inference function instead of just the model.
Only SegmentAnything train & inference and Stable Diffusion train are affected.
The rest relies on Trainer from HuggingFace or no custom train or inference functions (relies on the torch model call function).
Had to change the batch size for SegmentAnything inference since it runs OOM with the old batch size.

update torch compile settings

---

examples/nlp/abstractive_summarization_with_bart.py
examples/nlp/ipynb/abstractive_summarization_with_bart.ipynb
examples/nlp/md/abstractive_summarization_with_bart.md

This PR changes the [Abstractive Text Summarization with BART](https://keras.io/examples/nlp/abstractive_summarization_with_bart/) example to Keras 3.0
https://colab.research.google.com/drive/1lqtjRaiBrSlfdmlJPuHB8ifYAJFY96eb?usp=sharing
cc: @fchollet 
```
diff --git a/examples/nlp/abstractive_summarization_with_bart.py b/examples/nlp/abstractive_summarization_with_bart.py
index f712383e..fc14a4b0 100644
--- a/examples/nlp/abstractive_summarization_with_bart.py
+++ b/examples/nlp/abstractive_summarization_with_bart.py
@@ -42,8 +42,8 @@ pip install git+https://github.com/keras-team/keras-nlp.git py7zr -q
"""
"""
-This examples uses [Keras …
```

Migrating Abstractive Text Summarization with BART example to Keras 3

---

examples/nlp/parameter_efficient_finetuning_of_gpt2_with_lora.py

Correction of the merging code between the model's original layer weights and the LoRA model weights. This respect the principle of LoRA to dispose of the LoRA layers once we don't plan on training it more bur more importantly allows us to save and load the model as a ".keras" file.

Correct LoRA weights merging

---

examples/structured_data/ipynb/tabtransformer.ipynb
examples/structured_data/md/tabtransformer.md
examples/structured_data/tabtransformer.py

In `create_model_inputs`, the same inputs were created for both numeric and categorical variables, so I updated the dtype for categorical variables

Set input dtype to int32 for categorical features in tabtransformer example

---

examples/nlp/ipynb/ner_transformers.ipynb
examples/nlp/md/ner_transformers.md
examples/nlp/ner_transformers.py

Corresponding [Issue](https://github.com/keras-team/keras-io/issues/1795)
This PR updates the [Named Entity Recognition using Transformers](https://keras.io/examples/nlp/ner_transformers/) Keras 3.0 example [TF Only Backend]. Many TF ops are replaced with corresponding Keras ops.
https://colab.research.google.com/drive/10cfqKFFs0Fy9VilbV7CRGLOcD8tTpqf-?usp=sharing
cc: @fchollet 
```
diff --git a/examples/nlp/ner_transformers.py b/examples/nlp/ner_transformers.py
index c887c0bc..02f22c0b 100644
--- a/examples/nlp/ner_transformers.py
+++ b/examples/nlp/ner_transformers.py
@@ -37,8 +37,8 @@ import os
os.environ["KERAS_BACKEND"] = "tensorflow" …
```

Updated Named Entity Recognition using Transformers example for Keras 3

---

examples/generative/ipynb/vae.ipynb
examples/generative/md/vae.md
examples/generative/vae.py

This PR updates the [Variational AutoEncoder](https://keras.io/examples/generative/vae/) Keras 3.0 example [TF Only Backend]. All TF ops are replaced with corresponding Keras ops.
https://colab.research.google.com/drive/15VMQIEUK8jhqI8nYyFSfWDh9fsMMs116?usp=sharing
cc: @fchollet 
```
diff --git a/examples/generative/vae.py b/examples/generative/vae.py
index d1d195c9..3396f4f7 100644
--- a/examples/generative/vae.py
+++ b/examples/generative/vae.py
@@ -18,6 +18,7 @@ os.environ["KERAS_BACKEND"] = "tensorflow"
import numpy as np
import tensorflow as tf
import keras
+from keras import ops
from keras import layers
"""
@@ -30,10 +31,10 @@ class …
```

Updated Variational AutoEncoder example for Keras 3

---

examples/nlp/ipynb/neural_machine_translation_with_keras_nlp.ipynb
examples/nlp/md/neural_machine_translation_with_keras_nlp.md
examples/nlp/neural_machine_translation_with_keras_nlp.py
scripts/autogen.py

Fixes: https://github.com/keras-team/keras-io/issues/1840

update from end_token_id to stop_token_ids

---

scripts/docstrings.py

[PR #1608](https://github.com/keras-team/keras-nlp/pull/1608) moved code to `/src`

Fix links for keras_nlp

---

scripts/docstrings.py

like stated here:
https://github.com/keras-team/keras-io/blob/master/scripts/docstrings.py#L135
and here:
https://github.com/keras-team/keras-io/blob/master/scripts/autogen.py#L46
`project_url` always already has a trailing slash.

Fix source links aways contain an extra slash

---

guides/ipynb/keras_tuner/getting_started.ipynb
guides/keras_tuner/getting_started.py
guides/md/keras_tuner/getting_started.md
templates/api/metrics/index.md

The method is called reset_state in the source.
Source: https://github.com/keras-team/keras/blob/master/keras/src/metrics/metric.py

fix metric.reset_state spelling error

---

examples/keras_recipes/ipynb/parameter_efficient_finetuning_of_gemma_with_lora_and_qlora.ipynb
examples/keras_recipes/md/parameter_efficient_finetuning_of_gemma_with_lora_and_qlora.md
examples/keras_recipes/parameter_efficient_finetuning_of_gemma_with_lora_and_qlora.py
scripts/autogen.py

This example borrows a lot of description from https://keras.io/examples/nlp/parameter_efficient_finetuning_of_gpt2_with_lora/
Therefore, I have added the original authors as this example's authors.
Basically, this example demonstrates the fine-tuning of Gemma with LoRA and QLoRA on a French-to-English translation task.
Please let me know if the `.py` is ready. Then, I will submit the `.md` and `.ipynb`.
Note that we need the latest code from KerasNLP since the quantization support hasn't been released yet.
cc @fchollet

Add LoRA and QLoRA example

---

guides/ipynb/writing_your_own_callbacks.ipynb
guides/md/writing_your_own_callbacks.md
guides/writing_your_own_callbacks.py

Numpy 2.0 deprecates part of their namespace, see https://numpy.org/doc/stable/numpy_2_0_migration_guide.html for all details.
Keras is affected by **np.Inf** -> **np.inf**

Migrating numpy namespace to numpy 2.0 in writing_your_own_callbacks.py, .md and .ipynb files

---

scripts/hub_api_master.py

I tried to setup keras-io with docker and got following error.
command:
```
docker build -t keras-io . && docker run --rm -p 8000:8000 keras-io
```
error:
```
10.66 ...Processing api/keras_hub/preprocessing_layers/resizing_image_converter
10.66 Traceback (most recent call last):
10.66   File "/scripts/docstrings.py", line 121, in import_object
10.66     last_object_got = importlib.import_module(".".join(seen_names))
10.66   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
10.66     return _bootstrap._gcd_import(name[level:], package, level)
10.66   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
10.66   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
10.66   File "<frozen importlib._bootstrap>", line 984, in …
```

Fix autogen.py try to install removed layer

---

guides/ipynb/keras_hub/stable_diffusion_3_in_keras_hub.ipynb
guides/md/keras_hub/segment_anything_in_keras_hub.md
guides/md/keras_hub/stable_diffusion_3_in_keras_hub.md

I've noticed that the image urls are broken.
Instead of:
`https://keras.io/home/hongyu/workspace/keras-io/guides/img/stable_diffusion_3_in_keras_hub/stable_diffusion_3_in_keras_hub_7_0.png`
The correct url should be:
`https://keras.io/img/guides/stable_diffusion_3_in_keras_hub/stable_diffusion_3_in_keras_hub_7_0.png`
The issue might be in `autogen.py` but I'm not sure what the root cause is.
CC @divyashreepathihalli 
I've fixed the image urls in SAM as well.

Fix image urls

---

scripts/api_master.py

`STFTSpectrogram` is not part of Keras 3.6 yet and causing build failure, commenting the part till it will be available as part of next stable release.

fix build failure

---

guides/ipynb/keras_hub/stable_diffusion_3_in_keras_hub.ipynb
guides/keras_hub/stable_diffusion_3_in_keras_hub.py
guides/md/keras_hub/stable_diffusion_3_in_keras_hub.md

The SD3 guide needs to be updated once we have a new release of `keras-hub`, as https://github.com/keras-team/keras-hub/pull/1951 has been merged
cc @divyashreepathihalli

Use `image_shape` for SD3

---

templates/keras_cv/index.md

Small PR - fixes the `keras-cv` references in `templates/keras_cv/index.md`.

Update Keras CV references

---

scripts/autogen.py
scripts/render_presets.py

We had relative links that broke when we changed the site structure, switch to absolute links.
Also:
- Better sort order for preset table.
- Use less metadata in the table.

Fix preset table doc links

---

examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb
examples/nlp/md/neural_machine_translation_with_transformer.md
examples/nlp/neural_machine_translation_with_transformer.py

This pull request addresses several issues in the "English-to-Spanish translation with a sequence-to-sequence Transformer" code example:
1) Swapped input tensors:
- Issue: The encoder and decoder inputs were swapped, causing either the model to be trained in the wrong translation direction, or inference happening in the wrong direction.
- Fix: Aligned the encoder and decoder inputs correctly, so the model is trained and used to translate from English to Spanish. This results in meaningful translations when trained to convergence.
2) Padding handling:
- Issue: The padding masks were computed but never used.
- Fix: Propagate the masks out of the embedding layer.
- Fix: Updated the decoder to handle multiple masks, accommodating padding in both Spanish and English sequences.
- Fix: Modified …

Fixes to the "English-to-Spanish Translation with a Sequence-to-Sequence Transformer" Code Example

---

examples/vision/ipynb/shiftvit.ipynb
examples/vision/md/shiftvit.md
examples/vision/shiftvit.py
scripts/examples_master.py

This PR changes the [A Vision Transformer without Attention](https://keras.io/examples/vision/shiftvit/) example to Keras 3.0
For example, here is the notebook link provided: https://colab.research.google.com/drive/1tgIPW6DOux-dNicegYcnG8lnWswrE0Ji?usp=sharing
cc: @fchollet 
```
diff --git a/examples/vision/shiftvit.py b/examples/vision/shiftvit.py
index e0c42d1d..bd053246 100644
--- a/examples/vision/shiftvit.py
+++ b/examples/vision/shiftvit.py
@@ -27,11 +27,7 @@ operation with a shifting operation.
In this example, we minimally implement the paper with close alignement to the author's
[official implementation](https://github.com/microsoft/SPACH/blob/main/models/shiftvit.py).
-This …
```

A Vision Transformer without Attention example to Keras 3

---

guides/ipynb/keras_hub/semantic_segmentation_deeplab_v3.ipynb
guides/keras_hub/semantic_segmentation_deeplab_v3.py
guides/md/keras_hub/semantic_segmentation_deeplab_v3.md

Here in this semantic segmentation tutorial using Keras Hub, prediction will be on the test data. As we load the test data on this section I feel due to some typo it is taking the image from train data. This PR fixes that change.
cc: @fchollet

Typo fix dataset name

---

templates/api/losses/index.md

Make it clearer that losses reduce along the batch dimension

---

scripts/examples_master.py

We should update the highlight to replace KerasCV SD with KerasHub SD3.
https://keras.io/examples/generative/

Update the link to the example of the random walk for SD3

---

scripts/api_master.py

https://github.com/keras-team/keras/pull/20599 added these classes and it's now released, but they're missing from the API docs.
This PR adds them to the API tree.
Let me know if it's added in the right place.

Add sklearn wrappers to API docs

---

examples/vision/attention_mil_classification.py
examples/vision/ipynb/attention_mil_classification.ipynb
examples/vision/md/attention_mil_classification.md

Fixing the typo in attention_mil_classification files

Fixing the typo in attention_mil_classification.ipynb

---

templates/keras_3/keras_3_announcement.md
theme/landing.html

**Details:** Document OpenVINO backend support
cc: @fchollet, could you please take a look?

Document OpenVINO backend support

---

.github/workflows/auto-assignment.yaml
.github/workflows/continuous_integration.yml
.github/workflows/stale-issues-pr.yml

Fixes https://github.com/keras-team/keras-io/issues/1579.
This PR adds read-only permissions to continuous_integration.yml.
It also adds some future-proofing to the other workflows by moving write permissions to job-level instead of top-level, keeping only read-only top-level permissions. This way the added permissions aren't available to other jobs potentially added to the workflows in the future.

Token permissions

---

examples/generative/ipynb/gpt2_text_generation_with_keras_hub.ipynb
guides/ipynb/keras_cv/coco_metrics.ipynb
guides/ipynb/keras_tuner/custom_tuner.ipynb

Updated broken links in:
- examples/generative/ipynb/gpt2_text_generation_with_keras_hub.ipynb
- guides/ipynb/keras_cv/coco_metrics.ipynb
- guides/ipynb/keras_tuner/custom_tuner.ipynb

Updated broken links in jupyter notebooks

---

scripts/hub_master.py

The [KerasHub Model Architectures documentation](https://keras.io/keras_hub/api/models/) for the `Bart Model` incorrectly lists `BertTokenizer` and `BertBackbone model`.

Fix typo in `KerasHub Model Architectures` documentation under `Bart model`

---

.gitignore
examples/keras_recipes/approximating_non_function_mappings.py
examples/keras_recipes/ipynb/approximating_non_function_mappings.ipynb
examples/keras_recipes/md/approximating_non_function_mappings.md

Hi, 
this PR updates Mixture Density Network (MDN) example to user `keras` V3 instead of `keras-core` and JAX as backend.

convert MDN to KerasV3

---

examples/rl/actor_critic_cartpole.py
examples/rl/ipynb/actor_critic_cartpole.ipynb
examples/rl/md/actor_critic_cartpole.md

Fixed the provided code so it works with the newer versions of gym

Updated the Actor-critic example

---

requirements.txt
scripts/autogen.py

`tf-text` version `2.19` is released: https://pypi.org/project/tensorflow-text/2.19.0/#files
This resolves the conflict `tf` version conflict between `tf-keras` and `tf-text` so we don't have to pin `tf` and `tf-keras` versions to an older version anymore.

Update tf-keras version to 2.19

---

examples/structured_data/class_with_grn_and_vsn_with_hyperparameters_tuning.py
examples/structured_data/ipynb/class_with_grn_and_vsn_with_hyperparameters_tuning.ipynb
examples/structured_data/md/class_with_grn_and_vsn_with_hyperparameters_tuning.md

Find PR which addresses issue #2063.
In this PR, I attempt to leverage `Autokeras` and `KerasTuner` in the script `structured_data/classification_with_grn_and_vsn.py` to include `hyperparameters` tuning.
- From AutoKeras we construct blocks to add-in hyperparameters in the `__init__` method, and we also subclass from `Graph` to override the `build` method.
- We use the `HyperModel` and the `Tuner` classes from KerasTuner.
Please advise if the example still falls within the scope of `keras-io` examples so I may proceed to generate `.md` and `.ipynb` files.

New added example with hyperparameters tuning using Autokeras and KerasTuner

---

examples/keras_rs/basic_retrieval.py
examples/keras_rs/data_parallel_retrieval.py
examples/keras_rs/dcn.py
examples/keras_rs/deep_recommender.py
examples/keras_rs/ipynb/basic_retrieval.ipynb
examples/keras_rs/ipynb/data_parallel_retrieval.ipynb
examples/keras_rs/ipynb/dcn.ipynb
examples/keras_rs/ipynb/deep_recommender.ipynb
examples/keras_rs/ipynb/listwise_ranking.ipynb
examples/keras_rs/ipynb/multi_task.ipynb
examples/keras_rs/ipynb/sas_rec.ipynb
examples/keras_rs/ipynb/scann.ipynb
examples/keras_rs/ipynb/sequential_retrieval.ipynb
examples/keras_rs/listwise_ranking.py
examples/keras_rs/md/basic_retrieval.md
examples/keras_rs/md/data_parallel_retrieval.md
examples/keras_rs/md/dcn.md
examples/keras_rs/md/deep_recommender.md
examples/keras_rs/md/listwise_ranking.md
examples/keras_rs/md/multi_task.md
examples/keras_rs/md/sas_rec.md
examples/keras_rs/md/scann.md
examples/keras_rs/md/sequential_retrieval.md
examples/keras_rs/multi_task.py
examples/keras_rs/sas_rec.py
examples/keras_rs/scann.py
examples/keras_rs/sequential_retrieval.py

This is needed for the colabs to work.

Add `pip install keras-rs` to all examples that need it.

---

examples/audio/transformer_asr.py

**Description:**
In the train_step and test_step methods of the Transformer class, there's a reference to model.compute_loss() which should be self.compute_loss() instead. Since we're inside the class methods, we should use self to refer to the current instance of the model.
**Files Changed:**
[transformer_asr.py](https://github.com/keras-team/keras-io/blob/master/examples/audio/transformer_asr.py#L182)
**Changes Made:**
Replaced model.compute_loss() with self.compute_loss() in both train_step and test_step methods
**Impact:**
This correction ensures proper access to the parent class's compute_loss method through the correct instance reference. The original code would raise a NameError since model is not defined in this context, while self properly refers to the current Transformer …

Fix incorrect reference to model in Transformer class

---

guides/md/orbax_checkpoint.md
guides/orbax_checkpoint.py

Formatting issue:
Also removed a warning that was printed in the `.md` file.

Fix formatting issues in the Orbax guide

---

examples/keras_rs/distributed_embedding_jax.py
examples/keras_rs/ipynb/distributed_embedding_jax.ipynb
examples/keras_rs/md/distributed_embedding_jax.md

- Add `pip install`s
- Cast counts to int to not use `np.array`s in configuration

Tweaks to `DistributedEmbedding` for JAX example.

---

theme/base.html

Every page had a fixed `<meta name="description" content="Keras documentation">` tag. It now contains the title of the page, which is more specific because it has the API name for instance.
Google search in particular looks at this tag, and this tag only, for indexing [Documentation](https://developers.google.com/search/docs/crawling-indexing/special-tags#meta-tags). The hope is that it will improve search results.
This also makes it consistent with other meta tags like `<meta property="og:title" content="...">`.

Update meta description tag to contain the specific title of the page.
